ampproject/amp-github-apps

.editorconfig
.eslintignore
.eslintrc
.lgtm.yml
.travis.yml
build-system/exec.js
build-system/pr-check.js
bundle-size/app.js
bundle-size/package-lock.json
bundle-size/package.json
bundle-size/setup-db.js
package-lock.json
package.json

Add configuration files for:
* ESLint
* LGTM
* Travis
Also adds a `pr-check.js` file that will, for now, execute only `eslint` (but later will also run tests)

Add configuration files for CI checks and fix code to conform

---

bundle-size/app.js
bundle-size/test/app.test.js
bundle-size/test/fixtures/requested_reviewers.json

Add an OWNERS reviewer to a pull request that goes above the auto-approved bundle size

---

bundle-size/app.js
bundle-size/test/app.test.js

This will allow us to approve PRs that failed to get its bundle size delta calculated for any reason (e.g., missing GitHub webhook, botched `master` Travis build)
e.g., I couldn't approve this PR because the check.delta field was null https://github.com/ampproject/amphtml/pull/19703

Allow approving PRs with missing size delta

---

bundle-size/app.js
bundle-size/test/app.test.js

Add verbose descriptions to the various bundle-size status checks on GitHub

---

bundle-size/app.js
bundle-size/test/app.test.js

This fixes the issue where a PR gets reported twice from GitHub (happens on occasion, not 100% sure why but I think it might have to do with how PRs can transition through a state where they were created in the UI but not yet added to the repository)

bundle-size: update an existing check row with new check_run_id, when the head_sha already exists

---

bundle-size/app.js

Followup from changed introduced in https://github.com/ampproject/amphtml/pull/20811

Update bundle-size calculation description text

---

bundle-size/app.js
bundle-size/test/app.test.js

Let's celebrate when we shrink that bundle! 🎉

Encourage bundle-shrinking humans with emoji

---

bundle-size/setup-db.js

bundle-size: update log statement in `db-setup.js`

---

test-status/api.js
test-status/db.js
test-status/setup-db.js
test-status/test/api.test.js
test-status/test/web.test.js
test-status/views/status.hbs
test-status/web.js

To be reported if the tests had an infrastructure error instead of actual tests failing

Add an errored state to the test-status

---

test-status/api.js
test-status/db.js
test-status/setup-db.js
test-status/test/api.test.js
test-status/test/web.test.js
test-status/test/webhooks.test.js
test-status/views/status.hbs
test-status/web.js
test-status/webhooks.js

Rename database fields from snake_case to camelCase

---

bundle-size/app.js
bundle-size/package-lock.json
bundle-size/package.json
bundle-size/test/app.test.js
test-status/package-lock.json
test-status/package.json
test-status/test/api.test.js
test-status/test/web.test.js
test-status/test/webhooks.test.js

With required changes to make tests work. See: https://github.com/probot/probot/issues/883#issuecomment-483012748

Update dependency probot to v9

---

test-status/api.js
test-status/test/api.test.js

Restore `'action_required'` conclusion on failures

---

.eslintignore
build-system/exec.js
bundle-size/app.js
bundle-size/test/app.test.js
package-lock.json
package.json
test-status/api.js
test-status/db.js
test-status/test/webhooks.test.js
test-status/web.js

Renovate-bot automated upgrade failed because of required manual changes, this PR adds those changes

Update dependency eslint-plugin-jsdoc to v7.2.3

---

project-metrics/metrics_service/app.yaml
project-metrics/metrics_service/cron.yaml
project-metrics/metrics_service/metrics/base.py
project-metrics/metrics_service/server.py

Project Metrics: Add cron server and initial cron config

---

test-status/.env.example
test-status/README.md
test-status/api.js
test-status/db.js
test-status/setup-db.js
test-status/test/api.test.js
test-status/test/web.test.js
test-status/web.js

* store active build cop in db
* allow build cop updates through the API
* allow active build cop to use the web ui

test-status: add build cop handling

---

project-metrics/metrics_service/database/models.py
project-metrics/metrics_service/metrics/base.py
project-metrics/metrics_service/metrics/presubmit_latency.py
project-metrics/metrics_service/metrics/presubmit_latency_test.py
project-metrics/metrics_service/metrics/travis_greenness.py
project-metrics/metrics_service/metrics/travis_greenness_test.py

Syncs with levels in design doc.

Project Metrics: Add additional level to metric scores

---

project-metrics/metrics_service/app.yaml
project-metrics/metrics_service/server.py
project-metrics/metrics_service/templates/metric_guage.html
project-metrics/metrics_service/templates/show_metrics.html

App currently live at https://amp-project-metrics.appspot.com/

Project Metrics: Add a display page for project metrics

---

test-status/api.js

Partial fix for #85 (still missing: changes to Travis task runner on `amphtml`)

[test-status] Print Travis job URL when available

---

pr-deploy/package.json

[pr-deploy] Use tsc instead of local/tsc.js

---

test-status/auth.js

To enable logging in with GitHub via AppEngine
https://github.com/expressjs/session#saveuninitialized

[test-status] set saveUninitialized to true

---

test-status/auth.js

Revert #324

---

test-status/auth.js
test-status/package-lock.json
test-status/package.json
test-status/web.js

Fixes login issue that relates to the parallelization of processes on AppEngine + prematurely deleting the redirectTo value from the session object...

[test-status] Store sessions in database

---

owners/src/owners.js
owners/src/reviewer_selection.js
owners/test/owners.test.js

Add support for wildcard ownership rules

---

bundle-size/app.js
bundle-size/test/fixtures/check_run.created.json

Followup to #321 which changed the logic but forgot to change the text output

[bundle-size] :%s/gzipped/brotli/ in text output

---

pr-deploy/src/app.ts

casts a string to number to unblock https://github.com/ampproject/amp-github-apps/pull/345

Fix type in pr-deploy

---

owners/src/github.js
owners/test/github.test.js

Fixes issue where it was not using the latest review status.

[owners] Deserialize date of reviews from github

---

owners/index.js

Got left behind when the OwnersCheck constructor signature changed.

Fix PR check endpoint on health check

---

owners/src/github.js
owners/src/owners_check.js
owners/src/types.js
owners/test/fixtures/files/file_blob.24523.json
owners/test/github.test.js
owners/test/owners_bot.test.js
owners/test/owners_check.test.js

Step towards the Owners Syntax check, which will require fetching the modified OWNERS file(s).

Add method to GitHub interface for fetching file contents

---

owners/src/owner.js
owners/src/owners_bot.js
owners/src/owners_check.js
owners/src/owners_tree.js
owners/src/types.js
owners/test/owner.test.js
owners/test/owners_bot.test.js
owners/test/owners_check.test.js
owners/test/owners_tree.test.js

Also includes methods in the Owners Bot to use these modifiers to determine the set of reviewers to request and owners to notify/tag in the PR
Part of #395

Adds always- and never-notify modifiers to Owner class

---

owners/src/parser.js
owners/test/parser.test.js

[owners] Add support for parsing owner modifiers

---

owners/src/owners_check.js
owners/test/github.test.js
owners/test/index.test.js
owners/test/owners_check.test.js

Includes link to example OWNERS.yaml file: https://github.com/ampproject/amp-github-apps/blob/master/owners/OWNERS.example.yaml

Add help text to check-run output text

---

owners/test/github.test.js
owners/test/local_repo.test.js
owners/test/owners_bot.test.js

[owners] Replace `expect(true).toBe(true)` with `done` callback

---

owners/src/github.js
owners/src/owners_bot.js
owners/test/github.test.js
owners/test/owners_bot.test.js

[owners] Update existing bot comment when one exists if PR updates

---

bundle-size/app.js
bundle-size/test/app.test.js
bundle-size/test/fixtures/check_run.created.json

Reverted in #412, ready to be unreverted

[bundle-size] Unrevert #321 and #399

---

owners/src/parser.js
owners/test/parser.test.js

[owners] Add support for parsing `required: true` owner option

---

bundle-size/app.js

[bundle-size] Remove optional .json suffix from /store endpoint

---

bundle-size/app.js
bundle-size/test/app.test.js

Add a /report.json endpoint to receive a complete bundleSizes JSON object

---

owners/index.js

I'm not sure why this was here originally, but it's no longer needed and clogs up the logs.

[owners] Remove annoying double-logging

---

owners/example.env
owners/gce/startup-script.sh
owners/index.js

[owners] Read environment from dotfile

---

owners/gce/startup-script.sh

Couple small script changes after validating with a deployment this morning.

[owners] Sync repo startup script with latest working script

---

owners/index.js
owners/src/github.js
owners/src/notifier.js
owners/src/owner.js
owners/src/owners_bot.js
owners/src/owners_check.js
owners/src/owners_tree.js
owners/src/parser.js
owners/src/repo.js
owners/src/reviewer_selection.js
owners/src/rules.js
owners/src/types.js
owners/test/repo.test.js

This PR:
- migrates uses of `{type[]}` to `{!Array<!type>}`
- adds `!` to `@return` declarations
- fixes some optional paramater docs

[owners] JSDoc updates

---

owners/index.js
owners/src/file_cache.js
owners/test/file_cache.test.js
owners/test/github.test.js
owners/test/index.test.js
owners/test/repo.test.js

This is a small change to make room for the in-memory file cache to warm up from Cloud Storage on application startup.
Part of #540

[owners] Await app initialization before handling webhooks

---

owners/index.js
owners/scripts/warm_cache.js
owners/src/file_cache.js
owners/src/owners_bot.js
owners/src/repo.js
owners/src/types.js
owners/test/cloud_storage.test.js
owners/test/index.test.js
owners/test/owners_bot.test.js
owners/test/repo.test.js

This PR:
- adds the caching layers to the virtual repository
- adds a script to warm up the Cloud Storage cache with rate-limited requests to the GitHub API, to prevent overloading the API on app startup
Part of #540

[owners] Use cache in virtual repo and warm up cache

---

owners/index.js
owners/src/file_cache.js
owners/src/owners_bot.js
owners/src/repo.js
owners/test/file_cache.test.js
owners/test/repo.test.js

This PR addresses a handful of small cleanups, improving tests and logging and simplifying a couple bits and pieces.

[owners] General cleanup of small things

---

owners/scripts/warm_cache.js
owners/src/repo/virtual_repo.js

Also fixes a bug where the `syncTeams` function was not `await`ing a promisified `sleep` call

[owners] Move cache warmup logic to virtual repo

---

owners/package-lock.json
owners/package.json
owners/test/cache/compound_cache.test.js

[owners] Update Jest to latest version

---

test-status/package-lock.json

Fix performed via `npm audit fix`
Closes #270

Fix `set-value` dependency vulnerability

---

bundle-size/app.js
bundle-size/test/app.test.js

I know markdown! Who says I'm doesn't?!!?!

[bundle-size] Fix markdown issues

---

owners/src/owners_check.js
owners/test/owners_check.test.js

Addresses #596 
Separated from #599 given the simplicity of the change/ease of review

[owners] Report errors with a `failure` conclusion

---

README.md
pr-deploy/README.md

See [the branch README](https://github.com/rcebulko/amp-github-apps/tree/docs) for the Markdown-rendered view.

Add app descriptions to root README

---

bundle-size/app.js
bundle-size/test/app.test.js

[bundle-size] Remove optional .json suffix from /report endpoint

---

owners/index.js

Closes #630 and satisfies @danielrozenberg

[owners] Add "DO NOT REVIEW" as an auto-assign blocker

---

project-metrics/metrics_service/bootstrap.py
project-metrics/metrics_service/cron.yaml
project-metrics/metrics_service/database/models.py
project-metrics/metrics_service/metrics/__init__.py
project-metrics/metrics_service/metrics/cherrypick_issue_count.py
project-metrics/metrics_service/metrics/cherrypick_issue_count_test.py
project-metrics/metrics_service/server.py

[project metrics] Add CherryPickIssueCount metric

---

bundle-size/github-utils.js
bundle-size/test/webhooks.test.js
bundle-size/webhooks.js

#617
For now this only logs the results, but does not assign or resolve the check - checks are resolved using the legacy logic until we're satisfied with the logs

[bundle-size] Verify whether a pull request is approved by a reviewer using the `approving_teams` field

---

bundle-size/webhooks.js

[bundle-size] Await for async method `isBundleSizeApprover`

---

bundle-size/github-utils.js
bundle-size/webhooks.js

[bundle-size] Also include super users when determining bundle size approvers

---

bundle-size/github-utils.js

[bundle-size] Add log for when an approver is already a reviewer

---

bundle-size/api.js
bundle-size/test/api.test.js

Turns out I never actually stored the list of approving teams to the database; only assumed they are already saved in unit tests 😅
/cc @jackbsteinberg this should fix the issue you noticed!

[bundle-size] Store approving teams to the database when they are determined

---

test-status/.gitignore
test-status/cloud_build.yaml
test-status/package.json
test-status/redacted.env

[test-status] Add cloud deploy config

---

owners/src/ownership/owners_check.js

Closes https://github.com/ampproject/amphtml/issues/26603

Add link to owners tree from check-run output

---

invite/jest.config.ts
invite/package-lock.json
invite/package.json
invite/src/github.ts
invite/src/types.ts
invite/test/fixtures/add_member.exists.json
invite/test/fixtures/add_member.invited.json
invite/test/github.test.ts

Taking a test-driven approach, defining all the class interfaces and expectations first, then filling in the implementations, so as to allow for better parallelism

Add method stubs and tests for GitHub API interface

---

invite/package-lock.json
invite/package.json
invite/src/github.ts
invite/test/github.test.ts

```
GitHub interface
inviteUser
✓ PUTs to /orgs/:org/memberships/:username (19ms)
✓ returns true when the user is invited (2ms)
✓ returns false when the user is already a member (1ms)
addComment
✓ POSTs comment to /repos/:owner/:repo/issues/:issue_number/comments (2ms)
assignIssue
✓ POSTs assignee to /repos/:owner/:repo/issues/:issue_number/assignees (1ms)
```

[invite] Implement GitHub API interface methods

---

owners/index.js
owners/test/index.test.js

Disable "notify owner" comments on draft PRs

---

project-metrics/metrics_service/database/models.py

Fixes a query that SQLAlchemy was complaining about in the logs

Fix cherry-pick issue scraping DB query

---

owners/index.js

Abort owners checks on all draft PRs

---

owners/src/notifier.js
owners/test/notifier.test.js

[owners] wrap owners bot comment file lists in code blocks

---

release-calendar/.env.example
release-calendar/README.md
release-calendar/package-lock.json
release-calendar/package.json
release-calendar/src/app.ts
release-calendar/src/entities/release.ts
release-calendar/tsconfig.json

Uses [TypeORM](https://github.com/typeorm/typeorm) to interface with a MySQL database. Opted for this over knex for its TypeScript support.
Uses a `.env` file. Updates README for instructions on starting local dev.
Related to https://github.com/ampproject/amp-github-apps/issues/722

[release-calendar] Connect to a MySQL db with TypeORM

---

DEPLOYMENT.md

Swap Cloud Build/KMS hyperlinks

---

owners/src/reviewer_selection.js
owners/test/reviewer_selection.test.js

Closes https://github.com/ampproject/amp-github-apps/issues/499

[owners] Only suggest reviewers from the allowed reviewer set

---

release-calendar/src/client/models/view-models.ts
release-calendar/src/server/entities/promotion.ts
release-calendar/src/types.ts
release-calendar/test/repository-service.ts
release-calendar/test/test-data.ts

- removes fromChannel 
- renames toChannel to channel

[release-calendar] Updating db schema

---

release-calendar/package-lock.json
release-calendar/package.json
release-calendar/src/client/models/release-event.ts
release-calendar/src/client/stylesheets/_base.scss
release-calendar/src/client/stylesheets/app.scss
release-calendar/src/client/stylesheets/calendar.scss
release-calendar/src/client/stylesheets/channelTable.scss
release-calendar/webpack.client.config.js

This is will unify the location of the colors associated with each channel so to make the app easier to maintain.
Included:
- Fixed scss, which wasn't compiling into css correctly by installing `sass`
- Cleaned scss loading in `client.config`
- Added `_base.scss` to be a module that is loaded into other scss files
- Changed the colors associated with each channel (these ones have cooler names 😎)

[release-calendar] Change location of shared colors

---

error-issue/cloud_build.yaml
error-issue/index.ts
error-issue/package-lock.json
error-issue/package.json
error-issue/redacted.env
error-issue/src/error_monitor.ts
error-issue/src/stackdriver_api.ts
error-issue/src/types.ts
error-issue/test/error_monitor.test.ts

Part of https://github.com/ampproject/amphtml/issues/27675
The monitoring endpoint is designed to eventually be used with a GCP cron scheduler to periodically identify and report new issues, but won't be enabled until after design review. In the interim, the diagnostic endpoint serves as a tool to see which error issues are new and untracked, along with a link that can manually trigger creation of an issue if desired.
Top-down view:
```
PASS  test/error_monitor.test.ts
ErrorMonitor
newErrorsToReport
✓ ignores infrequent errors (4ms)
✓ ignores errors with an existing tracking issue (1ms)
✓ includes new frequent errors (1ms)
reportError
✓ reports the error to the error-issue endpoint (9ms)
✓ returns the URL of the created issue (2ms)
✓ throws an error when error creation fails (7ms) …
```

Add module to monitor errors in GCP and identify new untracked ones

---

error-issue/src/issue_builder.ts
error-issue/test/fixtures/created-issue.md
error-issue/test/issue_builder.test.ts

Part of https://github.com/ampproject/amphtml/issues/27675

[error-issue] Identify possible assignees for issues

---

error-issue/index.ts
error-issue/package.json
error-issue/src/stackdriver_api.ts

Somehow #801 ended up merging into a new branch; recreating here. Already has approval

[error-issue] Add auto-linking of created issue to GCP error

---

owners/src/api/github.js
owners/src/notifier.js
owners/test/api/github.test.js
owners/test/notifier.test.js

Closes https://github.com/ampproject/amp-github-apps/issues/799

[owners] Consolidate notification comments by grouping file lists

---

onduty/.eslintrc.js
onduty/.gcloudignore
onduty/.gitignore
onduty/README.md
onduty/cloud_build.yaml
onduty/index.ts
onduty/package-lock.json
onduty/package.json
onduty/redacted.env
onduty/tsconfig.json

Addresses https://github.com/ampproject/amp-github-apps/issues/778

[onduty] Add project boilerplate for onduty bot

---

onduty/package.json
onduty/src/github.ts
onduty/test/github.test.ts
onduty/test/jest-preload.ts
onduty/tsconfig.json
onduty/types/index.d.ts

Part of https://github.com/ampproject/amp-github-apps/issues/778

[onduty] Add GitHub API interface for fetching/updating team info

---

onduty/package-lock.json
onduty/package.json
onduty/src/bot.ts
onduty/test/bot.test.ts
onduty/types/index.d.ts

[onduty] Add Onduty Bot to handle rotation updates and update teams

---

onduty/cloud_build.yaml
onduty/index.ts
onduty/package.json
onduty/redacted.env
onduty/test/e2e.test.ts
onduty/types/index.d.ts

[onduty] Fix broken Travis (linting) & update env for production

---

error-issue/redacted.env
error-issue/src/bot.ts
error-issue/src/issue_builder.ts
error-issue/test/fixtures/created-issue.md
error-issue/test/issue_builder.test.ts

Uses the new groups added in https://github.com/ampproject/amp-github-apps/issues/778 to @ mention the release on-duty within error report issues

Tag release on-duty is error-issue bot issues

---

error-issue/src/error_monitor.ts
error-issue/test/error_monitor.test.ts

Paired change with https://github.com/ampproject/error-tracker/pull/133

Use new service name CDN 1%

---

error-issue/index.ts

By adding `preview=1` to the _Create Issue_ URL, the bot will respond with the issue payload (ie. title, body, etc. that would be sent to GitHub) rather than actually creating the new issue. Useful for testing/debugging without creating issues/tagging release on-duty

[error-issue] Add support for "preview" param in error issue bot

---

error-issue/index.ts
error-issue/package-lock.json
error-issue/package.json
error-issue/redacted.env
error-issue/src/issue_builder.ts
error-issue/src/utils.ts
error-issue/static/error-list.html
error-issue/types/error-issue-bot.d.ts

Adds Mustache template to render error list

---

error-issue/cloud_build.yaml
error-issue/index.ts
error-issue/static/error-list.html
error-issue/types/error-issue-bot.d.ts

Cleans up some plumbing and type definitions around the issue creation URL in the error list output

[error-issue] Simplify issue creation URL

---

owners/index.js
owners/src/api/github.js
owners/test/api/github.test.js
owners/test/info_server.test.js
owners/test/notifier.test.js
owners/test/owners_bot.test.js
owners/test/ownership/owner.test.js
owners/test/ownership/owners_check.test.js
owners/test/ownership/parser.test.js
owners/test/ownership/tree.test.js
owners/test/reviewer_selection.test.js

Closes https://github.com/ampproject/amp-github-apps/issues/685

[owners] Migrate Octokit calls from deprecated `listMembers` to `listMembersInOrg`

---

owners/src/notifier.js
owners/test/notifier.test.js

[owners] Truncate long file lists in notify comment

---

error-issue/app.ts
error-issue/index.ts
error-issue/src/error_monitor.ts
error-issue/types/error-issue-bot.d.ts

To make QA report generation a bit easier
Demo: http://20200529t165420-dot-amp-error-issue-bot.uc.r.appspot.com/top-issues

[error-issue] Add endpoint to list top error issues

---

bundle-size/api.js
bundle-size/common.js
bundle-size/setup-db.js
bundle-size/test/api.test.js
bundle-size/test/webhooks.test.js
bundle-size/webhooks.js

[bundle-size] show size delta even after approval

---

test-case-reporting/types/test-case-reporting.d.ts

/cc @rcebulko
Together with #896, works toward #882

Add typescript types for main models

---

test-case-reporting/.gitignore
test-case-reporting/index.ts
test-case-reporting/package-lock.json
test-case-reporting/package.json
test-case-reporting/redacted.env
test-case-reporting/src/db.ts
test-case-reporting/src/setup_db.ts

/cc @rcebulko 
Implements part of #882.
After running this script once against a postgres instance, the output of \d for each table is as follows:
`\d builds`
```
Table "public.builds"
Column    |           Type           | Collation | Nullable |              Default               
-------------+--------------------------+-----------+----------+------------------------------------
id          | integer                  |           | not null | nextval('builds_id_seq'::regclass)
commit_hash | character varying(40)    |           |          | 
pr_number   | integer                  |           |          | 
started_at  | timestamp with time zone |           |          | 
Indexes:
"builds_pkey" PRIMARY KEY, btree (id)
Referenced by:
TABLE "jobs" CONSTRAINT "jobs_build_id_foreign" FOREIGN KEY …
```

[test-case-reporting] Implement database initialization

---

test-case-reporting/tsconfig.json
test-case-reporting/types/test-case-reporting.d.ts

[test-case-reporting] Create types for interfacing with database

---

owners/src/ownership/parser.js
owners/test/ownership/parser.test.js

Prevents situations like https://github.com/ampproject/amphtml/pull/29001

[owners] Validate keys in owner/rule definitions

---

error-monitoring/redacted.env
error-monitoring/src/blame_finder.ts
error-monitoring/src/rate_limited_graphql.ts
error-monitoring/test/blame_finder.test.ts
error-monitoring/types/error-monitoring.d.ts

Finishes handling the GitHub timeout issue

[error-monitoring] Fix promise rejection handling for GraphQL calls

---

test-case-reporting/src/db.ts
test-case-reporting/src/setup_db.ts
test-case-reporting/src/test_result_record.ts
test-case-reporting/test/test_result_record.test.ts
test-case-reporting/test/testing_utils.ts
test-case-reporting/tsconfig.json
test-case-reporting/types/test-case-reporting.d.ts

/cc @rcebulko 
Closes #887 and #914

[test-case-reporting] Refactor query for test runs in a build, implement query for test case history

---

test-case-reporting/README.md
test-case-reporting/cloud_build.yaml
test-case-reporting/package.json

[test-case-reporting] Set up auto deployment

---

invite/src/invite_bot.ts
invite/test/e2e.test.ts
invite/test/invite_bot.test.ts

[invite] Add link to accept invite in invite bot comments

---

test-case-reporting/index.ts
test-case-reporting/package-lock.json
test-case-reporting/package.json

/cc @rcebulko @estherkim 
Closes https://github.com/ampproject/amp-github-apps/issues/890

[test-case-reporting] Store reports that are POSTed to endpoint

---

test-case-reporting/index.ts
test-case-reporting/package-lock.json
test-case-reporting/package.json

/cc @rcebulko @estherkim 
Works toward https://github.com/ampproject/amp-github-apps/issues/889

[test-case-reporting] Add json GET responses for standard queries

---

test-case-reporting/app.ts

[test-case-reporting] Add error handling to GET endpoints

---

test-case-reporting/test/e2e.test.ts
test-case-reporting/test/test_result_record.test.ts

Closes https://github.com/ampproject/amp-github-apps/issues/926.
I'm open to making this PR larger to cover more unhappy paths.

[test-case-reporting] Add unit tests for foreign key constraints

---

test-case-reporting/app.ts
test-case-reporting/app.yaml
test-case-reporting/redacted.env
test-case-reporting/src/db.ts
test-case-reporting/src/test_result_record.ts
test-case-reporting/test/e2e.test.ts
test-case-reporting/test/test_result_record.test.ts
test-case-reporting/types/test-case-reporting.d.ts

Not a very atomic PR, but all the tweaks are small.
Works toward #881

[test-case-reporting] Increase payload limit, fix typos & add missing settings

---

test-case-reporting/app.ts
test-case-reporting/package-lock.json
test-case-reporting/package.json
test-case-reporting/src/test_result_record.ts
test-case-reporting/static/test-run-list.html
test-case-reporting/test/test_result_record.test.ts
test-case-reporting/types/test-case-reporting.d.ts

Closes https://github.com/ampproject/amp-github-apps/issues/889

[test-case-reporting] Create mustache view templates

---

test-case-reporting/app.ts
test-case-reporting/cron.yaml

Closes https://github.com/ampproject/amp-github-apps/issues/886

[test-case-reporting] Stub cron config, add cron yaml

---

test-case-reporting/app.ts
test-case-reporting/cron.yaml

Closes https://github.com/ampproject/amp-github-apps/issues/892

[test-case-reporting] Add endpoint for cron task

---

error-monitoring/index.ts

Fix type of incoming query param

---

test-case-reporting/app.ts
test-case-reporting/static/test-case-list.html

Closes https://github.com/ampproject/amp-github-apps/issues/968

[test-case-reporting] Add view for test cases, sorted by stat

---

test-case-reporting/types/test-case-reporting.d.ts

Add e2e as possible test suite type (one-line enum change)

---

project-metrics/metrics_service/cron.yaml

[project-metrics] Add cron task to render two-year historylots

---

error-monitoring/static/error-list.html

Update instructions for handling duplicate errors

---

bundle-size/api.js
bundle-size/app.js
bundle-size/github-utils.js
bundle-size/package-lock.json
bundle-size/package.json
bundle-size/setup-db.js
bundle-size/test/api.test.js
bundle-size/test/webhooks.test.js

Tested using a local database, dev instance of the app, and a separate repo

[bundle-size] Update all dependencies, fix breaking changes, and modify tests to assert calls to Octokit instead of network calls

---

owners/src/notifier.js
owners/test/notifier.test.js

[owners] Notify owners with `required: true`

---

pr-deploy/package-lock.json
pr-deploy/package.json
pr-deploy/src/app.ts
pr-deploy/src/github.ts
pr-deploy/src/types/unzip-stream.d.ts
pr-deploy/test/app.test.ts

- Update dependencies
- Rewrite tests to use nock to intercept HTTP requests instead of mocking octokit, which is an internal dependency of probot
- Linting

[pr-deploy] Update dependencies and tests

---

pr-deploy/package-lock.json
pr-deploy/package.json
pr-deploy/src/github.ts

Use the "officially exported" types provided by Octokit. See https://github.com/octokit/rest.js/releases/tag/v17.0.0#typescript

[pr-deploy] Fix octokit types

---

owners/OWNERS.example
owners/package-lock.json
owners/package.json
owners/src/ownership/parser.js
owners/src/ownership/schema.json
owners/test/info_server.test.js
owners/test/ownership/parser.test.js

Closes #912 right on time, give or take five months :sweat_smile:

[owners] Use a JSON schema validator for OWNERS files

---

owners/package-lock.json
owners/package.json

Update `@google-cloud/storage` to fix a security issue in `node-forge` v0.9.2

[owners] Update @google-cloud/storage to fix security alert

---

renovate.json

[insert grumbling about clear documentation]

Renovate config %s/assignees/reviewers/

---

renovate.json

Links to the [Renovate Dependency Dashboard](https://github.com/ampproject/amp-github-apps/issues/1019)

Link from Renovate PRs to the dashboard issue

---

owners/bootstrap.js
owners/index.js
owners/package-lock.json
owners/package.json
owners/scripts/warm_cache.js
owners/src/api/github.js
owners/test/api/github.test.js
owners/test/index.test.js

I hate this pair of packages with every fiber of my being

[owners] Update octokit and probot packages together

---

error-monitoring/src/bot.ts
error-monitoring/test/bot.test.ts
error-monitoring/test/jest-preload.ts

Context: https://github.com/ampproject/amphtml/issues/31682#issuecomment-749175844
/cc @gmajoulet

[error-monitoring] Add project param to error go links

---

test-case-reporting/redacted.env

[test-case-reporting] Fix typo on env var

---

pr-deploy/app.yaml
pr-deploy/cloud_build.yaml
pr-deploy/redacted.env

Now you can trigger a deployment by pushing a tag described in the DEPLOYMENT doc

[pr deploy] Add cloud build

---

bundle-size/api.js
bundle-size/package-lock.json
bundle-size/package.json
bundle-size/test/api.test.js

[bundle-size] add support for glob patterns

---

bundle-size/api.js
bundle-size/test/api.test.js

[bundle-size] don't auto-tag @ampproject/wg-infra members on errored checks

---

bundle-size/api.js
bundle-size/test/api.test.js

[bundle-size] organize delta list into categories (require/don't require approval/missing)

---

bundle-size/package-lock.json
bundle-size/package.json

Because #1247 made me wonder what this is... 🤔

[bundle-size] Remove unused dependency `pino`

---

README.md
invite/test/fixtures/pull_request_review_comment.created.json
invite/test/fixtures/pull_request_review_comment.deleted.json
invite/test/fixtures/pull_request_review_comment.edited.json
test-status/api.js
test-status/redacted.env
test-status/test/api.test.js

Find-replace didn't catch these in #1250.

Replace more instances of `build cop` with `build on-duty`

---

build-system/pr-check.js

Saw this and it was bothering me

Remove extra steps in build-targets

---

.github/workflows/install_dependencies.sh
.github/workflows/pr-check.yaml
.vscode/settings.json
build-system/build-targets.js
build-system/ci.js
build-system/exec.js
build-system/git.js
build-system/log.js
build-system/pr-check.js
build-system/utils.js
package-lock.json
package.json

**PR highlights:**
- Get rid of the root dependency on `fancy-log` (it's part of `gulp` and isn't being maintained)
- Add `.vscode/settings.json` to enable auto-fix-on-save via the VSCode linter (if installed)
- Add a utilities file `build-system/utils.js` and move `timedExecOrDie()` to it
- Add a minimal `printChangeSummary()` function to print a change log (distilled version of what's in `amphtml`)
- Consolidate package installation and setup in `install_dependencies.sh` (necessary for change summary printing)
- Update process spawning functions in `exec.js` (current version of `spawnSync` was buggy on GH actions)
- Copy minimal versions of the necessary utils from the `amphtml` repo to `ci.js` and `git.js`
**Screenshot:**
Addresses …

Assorted infrastructure enhancements

---

owners/src/ownership/schema.json
owners/test/ownership/parser.test.js

Context: https://github.com/ampproject/amphtml/pull/34676#issuecomment-854039159

Update owners schema to allow bot owners

---

renovate.json

Turns out we need a few more fixes to make the grouping less granular. Also, some formatting / scheduling clean up.
Follow up to #1341

More grouping fixes

---

.eslintignore
pr-deploy/package-lock.json
pr-deploy/package.json
pr-deploy/src/app.ts
pr-deploy/src/github.ts
pr-deploy/test/app.test.ts

Updates app and tests to fix breaking changes introduced in v11

[pr-deploy] Upgrade probot to 11.4.0

---

renovate.json

Addresses https://github.com/ampproject/amp-github-apps/pull/1383#issuecomment-856836619
**Reference:** https://docs.renovatebot.com/configuration-options/#assignautomerge

Refine automerge assignment logic

---

test-status/api.js
test-status/app.js
test-status/package-lock.json
test-status/package.json
test-status/test/api.test.js
test-status/test/webhooks.test.js

Replaces #1354 and #1367 and fixes Probot usage

Test status package update

---

bundle-size-chart/package-lock.json
bundle-size-chart/package.json
bundle-size-chart/src/app.ts

* Update TS code to fix compilation errors
* Set max time to 6 months instead of 1 year (since versions older than 6 months are deleted anyways)

TS code updates for bundle-size-chart

---

release-calendar/src/client/components/ChannelTable.tsx
release-calendar/src/client/components/ReleaseCard.tsx
release-calendar/src/client/stylesheets/_base.scss
release-calendar/src/client/stylesheets/calendar.scss
release-calendar/src/client/stylesheets/channelTable.scss
release-calendar/src/server/repository-service.ts
release-calendar/src/types.ts
release-calendar/test/test-data.ts

To un-clutter the UI and change nightly to green instead of red

[release-calendar] Remove % and opt-in experimental channels

---

owners/src/api/github.js
owners/src/repo/virtual_repo.js
owners/test/api/github.test.js
owners/test/repo/virtual_repo.test.js

This seems like it should never have worked, and yet it's been running for 2 months. My best guess is that when I added in cache invalidation/refreshing logic, it was broken, but it never had occasion to trigger until a recent OWNERS file change or deletion, and once that code path finally ran it broke.

Fix bug breaking owners bot

---

project-metrics/README.md
project-metrics/metrics_service/database/db.py

The project-metrics project describes using a local SQL database but did not actually support doing so.

Update project-metrics db to support a local db

---

bundle-size-chart/package-lock.json
bundle-size-chart/package.json

Followup to #1511 that broke the build despite passing tests :/

Fix deps for bundle-size-chart

---

.eslintrc-ts.js
README.md
build-system/build-targets.js
percy-mirror-verifier/.eslintrc.js
percy-mirror-verifier/.gcloudignore
percy-mirror-verifier/README.md
percy-mirror-verifier/app.yaml
percy-mirror-verifier/cloud_build.yaml
percy-mirror-verifier/package-lock.json
percy-mirror-verifier/package.json
percy-mirror-verifier/redacted.env
percy-mirror-verifier/src/app.ts
percy-mirror-verifier/src/github.ts
percy-mirror-verifier/src/percy.ts
percy-mirror-verifier/src/server.ts
percy-mirror-verifier/src/webhooks.ts
percy-mirror-verifier/test/github.test.ts
percy-mirror-verifier/test/percy.test.ts
percy-mirror-verifier/test/server.test.ts
percy-mirror-verifier/test/webhooks.test.ts
percy-mirror-verifier/tsconfig.json
renovate.json

I created this app to attempt to catch Percy issues much earlier, such as the Percy bug that caused all Story visual diff tests to come up blank that took us 3 weeks to notice.
This app receives webhooks from Percy whenever a build is finished, and if it's a `main` branch build, it compares that build to the one that came from the PR that created the commit on `main`. If there are any differences, it will (later, after I'm satisfied that the logs catch the right type of issues) post a comment on the PR saying telling us the PR author to inspect the two builds
I know it's a lot of code to dump on you two in one go, lmk if you want to do an over-the-shoulder (over-video-chat) code review

Percy Mirror Verifier app

---

percy-mirror-verifier/src/percy.ts

Fixing post-review nit in #1562

[Percy Mirror Verifier] :%s/PercySnapshots/PercySnapshotsResponse/g

---

percy-mirror-verifier/package-lock.json
percy-mirror-verifier/package.json
percy-mirror-verifier/src/github.ts
percy-mirror-verifier/src/server.ts
percy-mirror-verifier/test/github.test.ts
percy-mirror-verifier/test/server.test.ts

Example of how such a comment would look: https://github.com/danielrozenberg/amphtml/pull/14#issuecomment-1022565330

[Percy Mirror Verifier] post a PR comment on PR/main disparity

---

.github/workflows/codeql.yml
error-monitoring/index.ts
error-monitoring/src/stackdriver_api.ts
invite/test/app.test.ts
percy-mirror-verifier/src/server.ts
test-case-reporting/app.ts

Add CodeQL workflow for GitHub code scanning

---

renovate.json

See #1458
Using `npx -q -p renovate renovate-config-validator`

Update renovate.json to v36's config schema

---

onduty/package-lock.json
onduty/package.json
onduty/test/e2e.test.ts

[On Duty] Replace `nock` in tests with direct mocking

---

.vscode/settings.json
bundle-size/cloud_build.yaml

Fix missing secretEnv
