- bundle-size/app.js
- bundle-size/package-lock.json
Deprecation warning:
```
DEPRECATED (@octokit/rest): `repos.getContent()` is deprecated, use `repos.getContents()`
```
> Rename getContent to getContents (octokit deprecation warning)

- bundle-size/.env.example
- bundle-size/.gitignore
- bundle-size/README.md
- bundle-size/db-config.example.js
Different environments (local vs. AppEngine) have radically different configs that it didn't make sense to keep inferring them from the `.env` file.
Instead I'd rather have a `db-config.js` file (in the `.gitignore` so it wouldn't be added to the repo) that just has the db connection config in it
> Modify database connection config to be defined in an explicit JS file

- bundle-size/app.js
This PR will cause the bundle-size app to retry reporting the bundle size of a PR every minute for 10 minutes, if the base SHA (i.e., branch point from master) is missing from the `ampproject/amphtml-build-artifacts` repo
This isn't going to block the PR checks on Travis for `ampproject/amphtml`, as the retries will happen in the background. The GitHub app will return an HTTP status of `200 OK` if successful immediately, or `202 CREATED` if it's going to retry instead
> Retry reports for 60 minutes when the base SHA is missing

- bundle-size/package-lock.json
- bundle-size/package.json
- bundle-size/test/app.test.js
This PR fixes some issues with the tests for the bundle-size app. Specifically:
* Tests will now receive a deep copy of JSON fixtures, so that they can modify them without changing the expectations of other tests
* Explicitly wait for network expectations, since async behaviours can cause those to seem to succeed in one test A but fail on the test B, despite the failure really occurring in test A
* Split the _delayed_ test cases to two cases, since one of them now includes extra network expectations that the other doesn't (to add an OWNERS reviewer, see #29)
> Fix how tests import fixtures and wait for network expectations

- bundle-size/app.js
- bundle-size/setup-db.js
- bundle-size/test/app.test.js
See https://github.com/ampproject/amphtml/pull/20153 for what this fixes. That PR must be merged before this one.
> bundle-size: expect calls to `/report` to contain an explicit `baseSha` field

- bundle-size/test/app.test.js
- test-status/test/api.test.js
- test-status/test/web.test.js
- test-status/test/webhooks.test.js
Test describe functions are not promises. This fixes a deprecation error that will turn into a failing error in a future version of Jest: https://travis-ci.org/ampproject/amp-github-apps/builds/505340784#L243-L244
> Remove async keyword from test describes

- bundle-size/package.json
- test-status/package.json
This will help ensure that we deploy to the correct project, since the `gcloud` tool does not allow per-directory configurations
> Add gcloud project to `npm run deploy` scripts

- bundle-size/app.js
- bundle-size/test/app.test.js
Looks like including emoji breaks the title.
So let's just remove it.
> Remove emoji from human-encouragement title

- test-status/README.md
- test-status/api.js
- test-status/db.js
- test-status/setup-db.js
- test-status/test/api.test.js
- test-status/test/web.test.js
- test-status/views/404.hbs
- test-status/views/status.hbs
- test-status/web.js
As suggested in https://github.com/ampproject/amphtml/pull/21407#discussion_r267410535
Note that I broke the database convention here from snake_case to camelCase, calling this field in the database `sub_type` to calling it `subType`. I'm planning on sending another PR soon to rename all of the database fields to camelCase so that they'll match the JavaScript style for variable names. I don't know why I didn't start that way, and since we don't have any real production data in this database yet I can just drop the tables and start over easily
> Add subtype to tests slug

- test-status/api.js
- test-status/test/api.test.js
I don't want the failures of the test-status bot to scare off people at first. Let's get everyone used to just seeing the errors before we restore the red × mark.
Created #102 to track reverting this
> Temporarily make all failures 'neutral' for test-status

- project-metrics/metrics_service/cron.yaml
- project-metrics/metrics_service/metrics/__init__.py
- project-metrics/metrics_service/metrics/base.py
- project-metrics/metrics_service/metrics/example.py
- project-metrics/metrics_service/metrics/presubmit_ignored.py
- project-metrics/metrics_service/metrics/presubmit_latency.py
- project-metrics/metrics_service/metrics/travis_greenness.py
- project-metrics/metrics_service/models.py
Since these metric implementations were written while metric registration and the cron server were pending CLs, they did not include these things in order to unblock review. This PR adds a helper scope to Builds, configures each metric, and cleans up a couple bugs introduced in a previous "Code review fixes" commit.
> Project Metrics: Add filters, metric registration, and cron configs to existing metrics

- project-metrics/metrics_service/apis/codecov.py
- project-metrics/metrics_service/apis/codecov_test.py
- project-metrics/metrics_service/apis/travis_test.py
These are not beautiful, but they make it easy to compare to the API docs and confirm that the right endpoints are being called in the right way.
> Project Metrics: Add tests for API modules

- test-status/package-lock.json
- test-status/package.json
- test-status/web.js
Redoing #191 from @renovate-bot but with the required change to avoid deprecation warnings
> Update dependency express-validator to v6

- project-metrics/metrics_service/server.py
The return value should be a `(response, status_code)`,  but in the endpoints using `jsonify` the parenthesis was in the wrong place so the return value became `((response, status_code), None)`
> Projec Metrics: Fix APi endpoint return values

- project-metrics/metrics_service/apis/travis.py
- project-metrics/metrics_service/metrics/presubmit_latency.py
- project-metrics/metrics_service/metrics/presubmit_latency_test.py
Also fixes scoring for presubmit-latency
> Project Metrics: Use wall-clock time for Travis build duration

- project-metrics/metrics_service/apis/codecov.py
- project-metrics/metrics_service/apis/codecov_test.py
- project-metrics/metrics_service/database/models.py
- project-metrics/metrics_service/metrics/absolute_coverage.py
- project-metrics/metrics_service/metrics/absolute_coverage_test.py
- project-metrics/metrics_service/metrics/base.py
- project-metrics/metrics_service/metrics/presubmit_latency.py
- project-metrics/metrics_service/metrics/release_cherrypick_count.py
- project-metrics/metrics_service/metrics/release_granularity.py
- project-metrics/metrics_service/metrics/travis_flakiness.py
- project-metrics/metrics_service/metrics/travis_greenness.py
The accuracy of results will depend on historical data being present, which is yet to be scraped. Historical metric computation will be a one-off backfill once the necessary historical data is scraped.
> Project Metrics: Enable support for metrics to compute historical metric results

- project-metrics/metrics_service/bootstrap.py
- project-metrics/metrics_service/metrics/absolute_coverage.py
- project-metrics/metrics_service/metrics/base.py
- project-metrics/metrics_service/metrics/presubmit_latency.py
- project-metrics/metrics_service/metrics/release_cherrypick_count.py
- project-metrics/metrics_service/metrics/release_granularity.py
- project-metrics/metrics_service/metrics/travis_flakiness.py
- project-metrics/metrics_service/metrics/travis_greenness.py
- project-metrics/metrics_service/scrapers/build_scraper.py
- project-metrics/metrics_service/scrapers/cherrypick_scraper.py
- project-metrics/metrics_service/scrapers/commit_scraper.py
- project-metrics/metrics_service/scrapers/release_scraper.py
I had thought `sqlalchemy.orm.scoped_session` was handling this, but it does not.
>  Project Metrics: Clean up DB session leak

- pr-deploy/env.example
- pr-deploy/package-lock.json
- pr-deploy/package.json
- pr-deploy/src/app.ts
- pr-deploy/src/github.ts
- pr-deploy/src/zipper.ts
- pr-deploy/test/app.test.ts
Updates the route URL to `travisbuilds` because that's how zipped build artifacts are named, `amp_dist_${travisBuildNumber}`.
Downgrades to nodejs10 because App Engine's standard environment only supports specific versions of nodejs, unlike the flexible environment which can support any of them. Opted for using the standard environment because it's :heavy_dollar_sign: free.99
Moved repo `owner` and `repo` to env variables because they're the same every time.
> [pr-deploy] Update POST route and downgrade to nodejs10 for App Engine standard env

- pr-deploy/src/app.ts
- pr-deploy/src/github.ts
- pr-deploy/src/zipper.ts
When a test site is deployed, the bot gives the user the working link, which is `https://console.cloud.google.com/storage/browser/amp-test-website-1/amp_dist_<travisbuildnumber>`
> [pr-deploy] Fix the URL when a test site is deployed

- owners/index.js
The `synchronize` event is whenever a PR is changed or commits are added. We had `synchronized`, so it wasn't re-triggering the owners check.
> Fix name of PullRequestEvent

- owners/index.js
There are a couple bugs in the existing OWNERS check (somewhere in `findClosestOwnersFile`, though I haven't yet identified the cause/fix) which result in an error being thrown when finding owners for a PR. Whatever the cause, the error results in no owners check ever being added to the PR. This PR catches any error and ensures a check-run is still added, but with a failure message and the error that was encountered.
The detail of this check-run (its status and text) will change soon as the bot becomes a blocking check/starts assigning reviewers, but since that won't be ready until the design review of the [reviewer selection algorithm](https://github.com/ampproject/amphtml/issues/24338), this will at least ensure that all PRs get owners checks and any errors are visible instead of …
> Create failed check-run if an error occurs

- .gitignore
- owners/index.js
- owners/src/github.js
- owners/src/owner.js
- owners/src/owners_check.js
- owners/test/github.test.js
- owners/test/index.test.js
- owners/test/owners.test.js
- owners/test/owners_check.test.js
One more (much smaller) refactor PR, pulling steps from the `Owner` class and `index.js` into the `OwnersCheck` class
> Pull main logic into OwnersCheck class

- owners/src/owners.js
- owners/src/owners_check.js
- owners/src/reviewer_selection.js
- owners/test/owners.test.js
- owners/test/owners_check.test.js
Rules themselves are strictly hierarchical, and since they'll only be applied to files that are already limited by ownership subtree, re-matching the path is redundant, repetitive, and redundant. `matchesFile` will now act as a filter, such as for globs and patterns. Basic owners rules have no filters, but upcoming rules supporting filetypes and filenames and other patterns will extend the `OwnersRule` class and may override the `matchesFile` test.
> Set up owners tree/rules/check to filter rules that match the file being tested

- owners/index.js
- owners/src/github.js
- owners/src/owners.js
- owners/src/owners_bot.js
- owners/src/owners_check.js
- owners/test/github.test.js
- owners/test/owners_bot.test.js
- owners/test/owners_check.test.js
This PR:
- Separates owners bot functionality out of `index.js`
- Adds a status check page (`/admin/status`)
- Adds a page to view the current OWNERS hierarchy (`/admin/tree`)
- *I cached this to prevent it being spammed and causing trouble, but I'm not sure if that's a real risk or not, and it's pretty hard to avoid with the next endpoint; opinions?
- Adds a page that generates the check-run for any PR, for testing/validation purposes.
> Adds a health-check server with app status, owners tree, and PR tests

- owners/src/owners.js
- owners/src/rules.js
- owners/test/index.test.js
- owners/test/owners.test.js
- owners/test/owners_check.test.js
- owners/test/reviewer_selection.test.js
- owners/test/rules.test.js
First step towards #278 
This PR adds the rule class that handles matching files based on a glob pattern. It also splits the definition of rule classes into a separate `rules` module.
Note that the parser does not yet create these pattern-based rules.
@danielrozenberg Again, this looks like a lot if you look at the files alone, but 90% of this PR is tests and moving code out into a new module.
> Add file matching for pattern-based rules

- owners/src/rules.js
- owners/test/owners.test.js
- owners/test/rules.test.js
Note that this only implements the test itself; parsing the difference between recursive and same-directory rules is a job left to the parser, and is yet to be implemented (just like with the `PatternOwnersRule`)
> Support same-directory only ownership rule patterns

- bundle-size/app.js
- bundle-size/test/app.test.js
Step 2.ii. in https://github.com/ampproject/amphtml/issues/21275
(repo-local issue: #142)
Do not merge until September 9th to let the repository collect a large enough set of base Brotli sizes
> Read .br files instead of gzipped (no extension) files

- owners/OWNERS.example.yaml
- owners/index.js
- owners/src/owners_check.js
- owners/src/parser.js
- owners/src/types.js
- owners/test/index.test.js
- owners/test/owners_check.test.js
- owners/test/parser.test.js
See the added `OWNERS.example.yaml` for supported syntax.
Closes #278 
Closes #282 
As a summary/guide to understanding and reviewing the parser, here is the Jest test summary for the module:
```
owners parser error
toString
✓ displays the file containing the error
✓ displays the error message
owners parser
parseOwnersFile
✓ reads the file from the local repository
✓ assigns the OWNERS directory path
✓ parses a YAML list
✓ parses a YAML list with blank lines and comments
team rule declarations
✓ returns no rule
✓ records an error
owner with a leading @
✓ parses ignoring the @ sign
✓ records an error
rule dictionary
✓ parses a single owner into a pattern rule
✓ parses a list of owners into a pattern rule
✓ reports errors for non-string owners
✓ starting with **/ parses into a recursive …
```
> Add support for glob and pattern parsing + improve testing and error handling

- owners/index.js
- owners/src/owners_bot.js
- owners/src/owners_check.js
- owners/test/owners_bot.test.js
- owners/test/owners_check.test.js
YARPR: Yet Another Refactor Pull Request
`OwnersCheck` has an `init` method which does asynchronous tasks like checking out the repo, reading/parsing from the filesystem, and fetching PR info from GitHub. The rest of the check runs synchronously. Since next steps include adding one or two more checks which will make use of some of the same things (files changed, ownership tree, reviewers/approvers), it's worth pulling this initialization into the `OwnersBot`, which will then pass it down to the `OwnersCheck` and eventually also the `DependencyOwnersCheck` and `OwnersSyntaxCheck`. This PR moves that initialization up, removes any `await`'s before `ownersCheck.run` (since it's no long async), and shifts all those initialization tests to the proper test file.
All files still have 100% test …
> Pull initialization from owners check into owners bot

- owners/src/owners_check.js
- owners/test/index.test.js
- owners/test/owners_check.test.js
With this, a failing check will have status 'failure' while a passing check will have status 'passing'. Currently, if there's an error, the status will remain 'neutral'. Possible statuses also include 'canceled' or 'action_required'. Do the current statuses seem fine, or do y'all have any suggestions on what should be adjusted?
> Make failing checks red on PR

- bundle-size/app.js
- bundle-size/test/app.test.js
> [bundle-size] Also write bundle size results to a JSON file

- owners/src/owner.js
- owners/src/owners_tree.js
- owners/src/parser.js
- owners/src/reviewer_selection.js
- owners/src/rules.js
- owners/test/index.test.js
- owners/test/owner.test.js
- owners/test/owners_check.test.js
- owners/test/owners_tree.test.js
- owners/test/parser.test.js
- owners/test/reviewer_selection.test.js
Paves the way for allowing modifiers of owners (see #395 ) like no-notify, always-notify, and require-review.
> Use Owner classes instead of username strings

- owners/src/github.js
- owners/src/owners_bot.js
- owners/test/fixtures/check-runs/check-runs.get.35.multiple.json
- owners/test/github.test.js
- owners/test/owners_bot.test.js
Since the OwnersBot will soon also run other checks (notably an owners-syntax-check and eventually a dependency-owners-check), this refactors the `getCheckRunId` method to return multiple check-run IDs instead of just the owners check-run ID.
> Update getCheckRunId to support multiple different checks

- owners/OWNERS.example.yaml
- owners/package.json
- owners/src/parser.js
- owners/src/rules.js
- owners/test/parser.test.js
- owners/test/rules.test.js
Recent updates to owners files highlighted that brace expansion would be useful, at which point it became worth it to use `minimatch`.
> Use `minimatch` to support brace expansion

- owners/index.js
- owners/src/owners_bot.js
- owners/src/owners_check.js
- owners/src/types.js
- owners/test/owners_bot.test.js
- owners/test/owners_check.test.js
For the purposes of selecting reviewers, assume that anyone already added to the PR will eventually approve it. Especially relevant in subsequent runs of the check, such as after new commits or reviewers adding approval.
> [owners] Handle requested and non-approving reviewers

- owners/src/owner.js
- owners/src/parser.js
- owners/test/parser.test.js
In some instances (such as validator files), certain types of files or directories should require reviews even when they have an owner's approval. In the case of validator files, even though they may live within individual extensions and could be approved by low-level owners, they should require approval from a member of wg-caching before submission. This PR adds that "gatekeeper" modifier.
> [owners] Add a "require review" modifier

- owners/src/github.js
- owners/src/owners_bot.js
- owners/test/fixtures/pulls/pull_request.35.json
- owners/test/github.test.js
- owners/test/owners_bot.test.js
In order to start testing out reviewer assignment without fully enabling it everywhere, this PR makes the Owners Bot use the PR description as a gatekeeper. If and only if the description contains `#addowners`, it will assign reviewers to the PR.
> [owners] Request reviewers if PR description contains #addowners

- owners/src/owners_bot.js
- owners/test/index.test.js
- owners/test/owners_bot.test.js
Owners specified as always-notify, ie. `!rcebulko`, should be tagged on a PR even if they are not a reviewer. This PR uses existing API interfaces to verify that such a comment does not yet exist, determine which users/teams should be notified for which files, and creates a PR comment tagging those users/teams.
> [owners] Create a comment tagging owners with the always-notify modifier

- owners/index.js
- owners/test/github.test.js
- owners/test/index.test.js
Bunyan logging evidently needs special treatment in order to properly log to GCE, but the code implementing this was still running during tests and made test output excessively verbose. This PR gates the `app.log.target.addStream` call, skipping if the node environment is `'test'`
> [owners] Disable stdout logging stream during test

- owners/src/github.js
- owners/src/parser.js
- owners/test/parser.test.js
Pull #437 added support for brace-set expansion, but that broke backwards-compatibility with comma-delimited rules since they could no longer be split by commas. Since the comma-separated form is already in use in the repo, this PR reverts to the original comma-separated functionality for rules which do not contain a brace `{}`, allowing existing comma-delimited rules to remain. Once this is submitted and deployed, I will update existing rules to use the brace-set syntax and remove this backwards compatibility (it is not documented in the [example file](https://github.com/ampproject/amp-github-apps/blob/master/owners/OWNERS.example.yaml))
> [owners] Add backwards compatibility for comma-separated rules without braces

- owners/index.js
- owners/src/reviewer_selection.js
- owners/src/rules.js
- owners/test/reviewer_selection.test.js
- owners/test/rules.test.js
In cases where pattern rules apply to files, owners of those patterns should be suggested before owners of the whole directory. This is especially relevant in cases of top-level pattern rules, which are currently being treated as equal with top level owners. This PR updates reviewer selection so that when multiple types of rules are present at the same depth, the most specific rules are the ones used to choose the next reviewer.
> [owners] Prioritize more specific rules during reviewer selection.

- owners/src/github.js
- owners/src/parser.js
@Enriqe raised the point that case-sensitivity could cause silent bugs in ownership. This PR sanitizes usernames by lowercasing them all at any points they enter the app--notably, either when parsing the owners files or through the few GitHub APIs which return usernames.
Ideally, we could overload the equality operator for owners to be case-insensitive; however, that's not supported in ES6, and much of the owners bot logic is written with maps, sets, `Array.includes(...)`, etc. which are all case-sensitive string comparison operations.
> Lowercase all usernames coming in via GitHub or parser

- owners/src/owners_bot.js
- owners/test/owners_bot.test.js
Currently, if the author is on the notify list, they'll get tagged in the notification comment. This PR removes them from the notification set for their own PR.
> Don't @mention the author in a notification comment

- owners/src/github.js
- owners/test/fixtures/comments/issue_comments.438.json
- owners/test/github.test.js
When GitHub responds with the list of comments, it appends `[bot]` to the bot's comment `login` field. As far as I can tell, this isn't documented anywhere, but it messes with the logic around identifying if a bot comment exists or not. This PR replaces checking for an exactly-equal username to just testing if the username is present in the `login` field, ignoring any (undocumented) suffixes.
> [owners] Handle undocumented bot username suffix

- owners/src/owners_bot.js
- owners/test/index.test.js
- owners/test/owners_bot.test.js
Ensures that the bot does not suggest new reviewers when the pending reviewers could provide owners coverage. The logic for this had been written already, it was just never wired together.
> [owners] Add pending reviewers to the current reviewer set

- owners/src/notifier.js
- owners/src/owners_bot.js
- owners/test/notifier.test.js
- owners/test/owners_bot.test.js
The logic keeping track of who to request and notify was getting complex and scattered enough to merit isolating it. This will make it easier to handle and test notifications separately from the owners check and will make updates like those required for #473 cleaner and more isolated. This PR makes no functional changes, and just shifts code/tests around.
In a follow-up PR addressing #473 , the `currentReviewers` field will be updated to reflect requested reviewers, and then used to filter out reviewers from the notification set. At this time, tests will be added addressing how the notifier handles pending/existing reviews.
Note: Rebasing onto #463 , which changed a signature to take a PullRequest instead of just a PR number, led to the commit history getting a bit tangled. As a result, …
> [owners] Migrate  review request and notif comment logic into new notifier class

- owners/src/github.js
- owners/test/fixtures/reviews/comment_reviews.24686.json
- owners/test/github.test.js
In looking at recent PRs in `ampproject/amphtml`,  I noticed that https://github.com/ampproject/amphtml/pull/24686 listed `@rsimha` as "requested" but not approved, even though he'd given an approving review already. Upon digging into this, I found that the GitHub Reviews API, in addition to returning reviews with expect states (ie. approved & changes requested), it was also including review comments with a "commented" state. This was not documented in the [REST API docs](https://developer.github.com/v3/pulls/reviews/), but is mentioned in the [GraphQL API docs](https://developer.github.com/v4/enum/pullrequestreviewstate/).
As a result, the logic which looks at the most recent review was mistakenly identifying comments as rejecting reviews. Upon reviewing the remaining possible states …
> [owners] Ignore irrelevant review states from GitHub

- owners/src/notifier.js
- owners/test/notifier.test.js
For the `amphtml` repository, the plan to to transition reviewer assignment from opt-in to opt-out; however, other repositories or users of the owners bot app may not want the same functionality. In addition, it is preferred to be able to toggle this through configuration rather than code changes.
This PR adds an `ADD_REVIEWERS_OPT_OUT` environment flag. When true, automatic reviewer assignment is enabled by default, and opted out with the `#noaddowners` tag; when false, automatic reviewer assignment does not run by default, and runs *only* when the `#addowners` tag is present (this is the current behavior).
> [owners] Add env flag to make reviewer assignment opt-in/opt-out

- owners/src/notifier.js
- owners/test/notifier.test.js
- owners/test/owners_bot.test.js
Suggestion: Review commit-by-commit
Currently, the notifier tags users regardless of whether or not they are already present on the PR. It already excludes the PR author from the notification comment; this PR also excludes any current, pending, or requested (newly pending) reviewers.
Closes #473
> [owners] Exclude pending and requested reviewers from the notification comment

- owners/index.js
- owners/package-lock.json
- owners/package.json
Exposes three endpoints: the status page; the ownership tree display; and the list of teams known by the app
Since none of these endpoints utilize the GitHub API, there is minimal risk to exposing them. By placing them on a dedicated server/port, the GCE firewall can be configured to allow traffic directly to that port.
> [owners] Expose status/info pages on separate port

- owners/package.json
- owners/src/github.js
- owners/src/owners_bot.js
- owners/test/fixtures/reviews/comment_reviews.24686.json
- owners/test/github.test.js
- owners/test/owners_bot.test.js
Closes #492 (see issue for more details)
The initial attempt to ignore comments completely backfired. This PR allows the GitHub interface to return comment reviews, adds far more comprehensive tests around how the owners bot treats different types of reviews in different orders, and fixes the issue.
> [owners] Treat comment-only reviews as rejections

- owners/index.js
- owners/src/owners_bot.js
- owners/test/owners_bot.test.js
Since the owners bot is webhooked to run after new commits or review status changes, it triggers when someone removes a reviewer, causing the bot to immediately reassign the reviewer. This could also be an issue when commits are added later on, re-adding previously removed reviewers. The desired behavior is instead that reviewer assignment should only occur upon PR creation. This means that you couldn't trigger assignment after the fact, but that's a reasonable trade-off since the owners check will still show suggested reviewers if more are necessary.
Closes #488
> [owners] Only request reviewers on new pull requests

- owners/index.js
Since the goal is to make the status server public-facing, it should not include any calls to rate-limited APIs or an filesystem I/O, as this presents a potential vulnerability to DOS/abuse. Currently, the only endpoint which has this issue is the `/tree` page, which displays the current ownership tree by parsing the locally checked-out repository on the GCE instance filesystem.
This PR instead creates a locally cached tree parse, which is updated on a regular (10 minute) interval, so that the public-facing endpoint does no filesystem I/O and just renders based on the in-memory tree parse.
> [owners] Cache tree parse on public-facing status server endpoints

- owners/src/parser.js
- owners/test/parser.test.js
Somehow I wrote all kinds of logic to catch and report syntax errors, yet I never handled YAML parsing errors. :man_facepalming:
> [owners] Catch YAML syntax errors in parser

- owners/index.js
- owners/package-lock.json
- owners/package.json
Apparently ServerJS ignores the `port` parameter if `PORT` is set on the environment (which it is, but for the probot app server). This switches to Express for the status server.
> [owners] Switch from ServerJS to Express for status server

- renovate.json
I think this is preferable for this repository, given that we have a lot of dependencies that get a `x.x.1` version update every few days...
> Set renovate-bot to update all packages in one PR, once a week

- bundle-size/app.js
- bundle-size/test/app.test.js
More changes included in this PR:
* Removes the text portion of the commit message now that the complete JSON is going to be included
* Reorganizes the tests into sub-sections using `describe`s. It might be easier to review these changes using a better diff program, such as Meld :) otherwise, trust that most of the test file changes is just shuffles (modulo required changes to the tests to cater to the aforementioned text removal), except for the addition of the `/commit/:headSha/store.json` test sub-section
> [bundle-size] Create new API endpoint to receive bundleSizes as a JSON payload

- owners/src/owners_check.js
- owners/test/owners_check.test.js
This PR adds support for checking required reviewers. It does not include parser changes to allow specifying required reviewers.
For context, see #516 
~Notably, this will also address #499 , since we can require approval from `ampproject/reviewers-amphtml` on all files.~
^^^ This won't work since that would make all reviewers owners of all files =/
> [owners] Adds support for required reviewers

- owners/src/owners_check.js
- owners/src/owners_tree.js
- owners/src/rules.js
- owners/test/owners_check.test.js
- owners/test/owners_tree.test.js
- owners/test/rules.test.js
Addresses #522 
This PR adds support for an optional reviewer set. It modifies the owners check to fail unless at least one approving review comes from a member of the "reviewer set". The reviewer set defaults to a wildcard owner, so by default it will do nothing. If a reviewer set rule is specified, it must be satisfied, or the check-run will have an `action_required` status with a message indicating that a reviewer is required.
This PR does not include any changes to reviewer suggestion logic, nor does it implement the actual parsing to produce a reviewer set rule. This will come in a future PR.
> [owners] Add support for an optional allowed reviewer set

- owners/OWNERS.example
- owners/src/parser.js
- owners/test/parser.test.js
Addresses #522 ; adds parser support for reviewer set added in #525 . Also includes update to example owners file.
> [owners] Add support for parsing the reviewer team option

- owners/src/github.js
- owners/test/fixtures/reviews/many_reviews.23928.page_1.json
- owners/test/fixtures/reviews/many_reviews.23928.page_2.json
- owners/test/github.test.js
- owners/test/index.test.js
Raised by https://github.com/ampproject/amphtml/pull/23928
The GitHub API returns reviews in chronological order, but in pages. For PRs with long/active conversation threads, this can mean that approvals end up on the second page, which the existing GitHub interface was not accounting for. This PR adds the API responses from this failing PR and tests around it, then adds the auto-paging to the GitHub interface.
> [owners] Bugfix: Auto-page reviews from GitHub API

- owners/gce/startup-script.sh
This updates the checked-in startup script to match the version living in the GCE metadata (minus any private keys), adds comments, and uses the private key as an env var directly instead of writing it to a file and passing the file path (Probot [accepts either format](https://probot.github.io/docs/configuration/))
Adresses #500
> [owners] Update startup script with (redacted) current startup script and reorganize

- pr-deploy/src/app.ts
- pr-deploy/src/github.ts
Closes #397
Gives a link to the actual deployed website instead of the Google Cloud Bucket.
Not tested (no idea how to test)
> [pr-deploy] Provide website url in addition to cloud bucket url

- owners/index.js
- owners/info_server.js
The purpose of this is two-fold. The first is simply cleanup; the info server kinda fell into place as a debugging tool, then `index.js` got a bit cluttered. The second is to enable easier testing, since the info server will eventually take on the role of providing a syntax-check API for Travis
> [owners] Split info server into standalone module

- owners/index.js
- owners/info_server.js
- owners/src/owners_bot.js
- owners/src/parser.js
- owners/test/owners_bot.test.js
Part of step 4 of #540 
Removes some dead code, cleans up some code around the parser and owners bot, and hoists the owners tree into a shared property of the owners bot singleton.
> [owners] Cleanup and hoist owners tree to shared property of owners bot

- owners/example.env
- owners/package-lock.json
- owners/package.json
- owners/src/cloud_storage.js
- owners/src/file_cache.js
- owners/test/cloud_storage.test.js
- owners/test/file_cache.test.js
This PR:
- adds a Cloud Storage API interface to upload, download, and delete files
- adds a Cloud Storage cache layer which tries to download from the cache before executing the provided function
- adds a memory cache which keeps a local copy of file contents
- adds a compound cache which first checks the memory cache, then the cloud storage cache
- includes tests
For a high-level view of what each class in this PR does, see the Jest output below:
```
PASS  test/cloud_storage.test.js
cloud storage
file
✓ provides a reference to a file in the storage bucket (5ms)
file operations
download
✓ downloads the file contents as a string (17ms)
upload
✓ saves the file contents (9ms)
delete
✓ deletes the requested file (8ms)
PASS  test/file_cache.test.js
file caches
Cloud Storage-backed
readFile …
```
> [owners] Add Cloud Storage interface and caches

- owners/index.js
- owners/info_server.js
Since it's useful to be able to spin up the info server as a standalone server separate from Probot (particularly for development and testing purposes), this PR converts the info server into a class and provides the ability to run the file/server directly, without needing the full Probot app to be run.
> [owners] Convert info server into a class

- owners/src/github.js
- owners/test/github.test.js
When I originally wrote these tests, I wasn't familiar with Jest and I didn't know how to create a GitHub client instance without faking a Probot event and getting it from the context. Spinning up all those apps for each test made it pretty slow, especially as the class grew to contain many API methods (~6.5s to run all tests).
This PR swaps in an Octokit instance and removes the dependency on Probot, bringing the test runtime down to ~1.5s
> [owners] Remove dependency on Probot when testing GitHub API

- owners/package-lock.json
- owners/package.json
I've been having the problem for a while where Octokit was not authenticating properly, despite following the docs. I discovered it was related to the older version of Probot relying on a version of Octokit from before the [constructor-based auth argument](https://github.com/octokit/rest.js/issues/1207) was available. This PR upgrades Octokit so we can rely on the constructor parameter.
> [owners] Update @octokit/rest to fix authentication issues

- owners/scripts/warm_cache.js
- owners/src/owners_bot.js
- owners/src/repo/virtual_repo.js
- owners/test/repo/virtual_repo.test.js
This PR adds an optional callback to the virtual repo `readFile` method. This allows scripts like the cache warmup to sleep in between cache misses, but plow straight through cache hits.
> [owners] Add callback for virtual repo cache misses

- owners/bootstrap.js
There have been a few cases where tests passed locally because they read from a `.env` file, but since those env vars weren't stubbed the tests failed on Travis. This PR gates the `require('dotenv').config()` call so it doesn't initialize the environment when `NODE_ENV` is `test`
Also cleans up bootstrap function.
> [owners] Don't read .env file during tests

- owners/bootstrap.js
- owners/index.js
- owners/info_server.js
- owners/src/cache/cloud_storage_cache.js
- owners/src/cache/memory_cache.js
- owners/src/owners_bot.js
- owners/test/index.test.js
- owners/test/owners_bot.test.js
This PR:
- replaces the local repo with a virtual repo
- warms up the virtual repo cache during bootstrapping/initialization
- unifies the info server using the express instance owned by Probot
> [owners] Migrate from local repo to virtual repo

- owners/info_server.js
- owners/src/repo/virtual_repo.js
- owners/test/repo/virtual_repo.test.js
This PR removes all repository-specific code for the owners bot, so it can work for any repo under a GitHub organization. It modifies the virtual repo to cache files using the repository name as the root directory. Since the GitHub interface is the only part of the bot that uses a repository, and since the app no longer requires checking out a copy of the repo onto the filesystem, this is all that's required on the implementation level to support other repos in the org. Since the bot instance currently holds the parsed owners tree, a few adjustments will need to be made to fully support additional repos.
> [owners] Make owners bot repository-agnostic

- owners/OWNERS.yaml
- owners/bootstrap.js
- owners/example.env
- owners/info_server.js
- owners/package-lock.json
- owners/package.json
- owners/scripts/warm_cache.js
- owners/src/owners_check.js
- owners/src/repo/virtual_repo.js
- owners/templates/example.template.html
- owners/templates/status.template.html
- owners/templates/teams.template.html
- owners/templates/tree.template.html
- owners/test/index.test.js
This PR:
- replaces info server endpoints that concatenated HTML with `lodash` template rendering
> Note that `lodash` is already a dependency of Probot
- Uses the OWNERS.example file as a syntax-highlighted documentation page
- Fixes a bug introduced by prefixing path names with the repository name
- Splits apart the repo owner and name in environment variables
- Removes the old OWNERS.yaml example
> [owners] Switch info server to template rendering and add OWNERS example file

- bundle-size/app.js
- bundle-size/test/app.test.js
Related to #271
This only adds a list of different files to the check output, but does not yet block on those other files
> [bundle-size] Report changes in bundle size of files other than `dist/v0.js`

- owners/src/api/github.js
- owners/test/api/github.test.js
- owners/test/index.test.js
This wasn't used previously because the outdated Octokit in the outdated Probot package used to cause breakages.
> [owners] Update GitHub API calls to use Octokit's `paginate` method

- owners/src/owners_check.js
- owners/test/api/github.test.js
- owners/test/owners_bot.test.js
- owners/test/owners_check.test.js
Closes #596 
Adds support for check-runs to have an "in progress" status. If a PR has reviews requested from enough OWNERS but they have not yet given approval, it will report an "in progress" status
> [owners] Add "in progress" as a possible check-run status

- owners/src/notifier.js
- owners/test/notifier.test.js
Currently, the owners bot handles the `requestReviews: false` modifier by determining the set of reviewers to request, then removing any with the silent modifier in any owners path. This has the following odd effect:
If I am an owner in `foo/OWNERS` with `requestReviews: false` as well as an owner in `bar/OWNERS` with no modifier, a PR touching both directories will not request me as a reviewer, even though I should be assigned because of my ownership of `bar`.
Likewise, if I am an owner in `OWNERS` with `requestReviews: false` as well as an owner in `bar/OWNERS` with no modifier, a PR touching `bar/foo.js` will not request me as a reviewer, even though I have not explicitly opted out of review requests in `bar`.
Both of these cases are counterintuitive. This PR first adds tests for each, …
> [owners] Better handling for `requestReviews: false`

- owners/app.yaml
- owners/src/api/github.js
- owners/src/owners_bot.js
- owners/test/api/github.test.js
The GitHub Search API is the only available way to find OWNERS files in the repo through the GitHub API. It is, however, non-deterministic, and often responds missing a few results. This PR:
- separates syncing the virtual repo's OWNERS file list from returning a list of owners files, ensuring files can't "go missing"
- switches the search pagination to use Octokit's built-in pagination
- syncs the virtual repository's OWNERS file list during initialization
- disables App Engine automatic scaling
> [owners] Fix GitHub Search and App Engine issues

- owners/info_server.js
- owners/src/cache/cloud_storage_cache.js
- owners/src/owners_bot.js
- owners/src/repo/virtual_repo.js
- owners/test/repo/virtual_repo.test.js
The GitHub Search API is the only available API method by which the virtual repo can determine the list of OWNERS files. Since this API is non-deterministic and often leaves out results, it's useful to keep a copy of the file ref list available, rather than fetching it from the API each time the tree is parsed. This PR updates the virtual repo to fetch the list of file refs through the cache, and updates the cache whenever it sees that a file ref sha has changed.
This means that even if the first request during warm-up doesn't catch all the owners files, each subsequent attempt will improve coverage, and the combination will be available going forward (even on system start-up, as it's cached in Cloud Storage).
> [owners] Fetch and save the set of known file refs through the cache

- build-system/build-targets.js
- build-system/exec.js
- build-system/git.js
- build-system/pr-check.js
- build-system/travis.js
- Transfers a lot of the helper functions for Git, Travis, and  `exec` directly from `ampproject/amphtml`
- Mimics the core logic/structure of build targets from `ampproject/amphtml`
- Defines build targets for each app
Closes #605
> Set up build targets for amp-github-apps

- owners/bootstrap.js
The hellcat preview allows the GitHub API's team members API to include nested teams. Originally this was set in code I'd written that manually ran custom requests, required for the outdated version of Octokit that shipped with the outdated version of Probot. The update to Probot 9 resulted in the update of Octokit, and the custom code was no longer needed. The header was never replaced, however, so nested teams broke.
> [owners] Add hellcat preview to Octokit initialization

- owners/info_server.js
- owners/src/owners_check.js
- owners/test/owners_check.test.js
A recent combination of owners rules let to an error thrown in reviewer selection for certain files, blocking PRs like https://github.com/ampproject/amphtml/pull/25639 and https://github.com/ampproject/amphtml/pull/25521 .
The underlying bug has been identified, but will take a bit longer to fix and test. This PR ensures that errors in reviewer selection do not report failed owners checks, and instead just give up on suggesting reviewers
> [owners] Don't report failure on reviewer selection errors

- owners/src/owners_tree.js
- owners/test/notifier.test.js
- owners/test/owners_tree.test.js
- owners/test/reviewer_selection.test.js
There is a bug in reviewer selection (sort of). It looks at the deepest OWNERS file rules for each file, and tries to look for reviewers in them. There are cases, however, where only pattern-based rules exist in `foo/OWNERS`, but those patterns may not apply to some files under `foo/`. Previously, this would cause reviewer selection to break, since it would think there were no reviewers available.
This was caused by a broken contract between what the reviewer selection algorithm is expecting in its input `fileTreeMap`. The `fileTreeMap` it was given mapped files to the closest OWNERS file, but did not care if that OWNERS file contained any rules that actually applied to the file.
This PR adds failing tests for reviewer selection and fileTreeMap construction, then patches the method on …
> [owners] Fix reviewer selection bug for non-matching rules

- bundle-size/.env.example
- bundle-size/README.md
- bundle-size/api.js
- bundle-size/package-lock.json
- bundle-size/package.json
- bundle-size/test/api.test.js
- bundle-size/test/fixtures/APPROVERS.json.json
Related to #617
Does the pre-processing, but doesn't actually do anything with it yet.
Tag-along changes:
* Better error messages in the log (`app.log(error)` gives a stack trace, ```app.log(`${error}`)``` does not)
* More log statements
* Fix a type in README.md
> [bundle-size] Fetch `APPROVERS.json` file from `ampproject/amphtml` and process bundle-size deltas with it

- bundle-size/api.js
The lengthy `try` statement causes the app to report that there was an error fetching the base SHA's bundle-size, but since the code continues to perform multiple other actions that could throw exceptions (like fetching APPROVERS.json, team IDs, team members, etc...) then that error message might be incorrect.
Failing to fetch the base SHA's bundle-size is *common*, because it might not have been computed yet (due to the `master` builds in Travis taking 2.5 hours) so we need to recover from that.
The failure of the other actions is *rare*, because those API endpoints are stable and predictable for the most part. In that case, I prefer that the entire request fail on an exception instead of reporting the wrong error.
This also makes writing tests easier, because network requests that …
> [bundle-size] Make the `try` statement in `tryReport` smaller

- project-metrics/metrics_service/database/models.py
- project-metrics/metrics_service/scrapers/__init__.py
- project-metrics/metrics_service/scrapers/cherrypick_issue_scraper.py
Provides a `CherrypickIssue` model and an associated `CherrypickIssueScraper`, which mimics the `CommitScraper` logic using the GitHub GraphQL API to populate the DB table.
Addresses #474
> [project metrics] Add scraping of cherry-pick commits

- bundle-size/setup-db.js
- bundle-size/test/webhooks.test.js
- bundle-size/webhooks.js
This preemption was necessary in the past, when the bundle-size checks were unstable. Eventually I'll return that ability only for `ampproject/wg-infra` so that we can still have somebody override it, but for #617 to work correctly this needs to go away
> [bundle-size] Prevent preemptive approvals for bundle-size changes

- bundle-size/api.js
- bundle-size/common.js
- bundle-size/github-utils.js
- bundle-size/setup-db.js
- bundle-size/test/api.test.js
- bundle-size/test/webhooks.test.js
Related to #617
Adds a new DB column and updates that column when the teams needed for approval are determined in the `/report` API endpoint. This data will be used in a followup-PR in the review webhook
Tag-along changes:
* Make tests more strict by switching db row comparisons from `toMatchObject` to `toEqual`, which fails on missing fields
* Fixed logging typo
> [bundle-size] Store the chosen approving teams in the database

- renovate.json
Relevant docs: https://docs.renovatebot.com/node/#configuring-support-policy
We use `lts_active` in `ampproject/amphtml`, but for `amp-github-apps` I think it makes sense to ride the front of the wave with `lts_latest`
> Let renovate-bot upgrade node version to latest LTS

- project-metrics/metrics_service/cron.yaml
- project-metrics/metrics_service/metric_plot.py
- project-metrics/metrics_service/server.py
- project-metrics/metrics_service/templates/show_metric_history.html
This adds a `history_days` optional param to the `/_cron/plot_metric_history`, `/api/plot/*Metric.png`, and `/history` endpoints to allow for generating and viewing results over various time windows
> [project metrics] Augment plotting to allow arbitrary range of results

- bundle-size/.env.example
- bundle-size/api.js
- bundle-size/github-utils.js
- bundle-size/test/api.test.js
- bundle-size/test/webhooks.test.js
#617
This will make it easier to switch to the new selection algorithm once the logs show that we're getting it right on the "dry-runs"
Tag-along changes:
* Update .env.example with a more accurate set of super-users
* Remove extended timeout for tests since they now pass fairly quickly
> [bundle-size] Move new reviewer selection logic into the `addBundleSizeReviewer` and move that method into `GitHubUtils`

- bundle-size/api.js
- bundle-size/github-utils.js
When I deployed the app after the changes in #646 this action threw permissions errors, I believe the user-based token can't add reviewers. In any case, it makes sense to do this via the app as this will say which bot added the reviewer, as opposed to just @ampprojectbot
Tag-along change:
* Remove node cache's standard TTL, as each cached object has its own TTL
> [bundle-size] Use the app-based GitHub token, not the user-based one, to add reviewers

- invite/package.json
- invite/src/github.ts
- invite/src/invitation_record.ts
- invite/src/types.ts
- invite/test/invitation_record.test.ts
Taking a test-driven approach, defining all the class interfaces and expectations first, then filling in the implementations, so as to allow for better parallelism
This invitation record will eventually contain an implementation backed either by Cloud SQL or Cloud Datastore, which will record invites as they are sent so that the bot can later update the threads and assign issues if/when the invites are accepted.
```
invitation record
recordInvite
✕ records an invite (1ms)
✕ sets `archived = false`
getInvites
if no invite record exists for the user
✓ returns an empty list (1ms)
if records exists of invites to the user
✕ returns the invites (3ms)
if only archived invite records exists for the user
✓ returns an empty list
archiveInvites
if records exists of any invites to the user
✕ updates …
```
> [invite] Add method stubs and tests for invitation record

- invite/src/invite_bot.ts
- invite/test/app.test.ts
- invite/test/fixtures/index.ts
- invite/test/invite_bot.test.ts
```
Invite Bot
parseMacros
✕ handles mix of `/invite` and `/tryassign` macros (1ms)
comments without macros
✓ returns an empty list (2ms)
✓ ignores macros without usernames
comments with `/invite @user`
✕ returns list including Invite action for @user (3ms)
✕ handles multiple `/invite` macros (7ms)
comments with `/tryassign @user`
✕ returns list including InviteAndAssign action for @user (3ms)
✕ handles multiple `/tryassign` macros (2ms)
tryInvite
when the user has a pending invite from the bot
✓ it does not attempt to send an invite (2ms)
✕ records the requested invite (5ms)
✕ comments that there is already an invite pending (1ms)
when the user is a member
✕ attempts to send an invite (1ms)
✓ does not record the requested invite
✕ comments that the user is already a member (2ms)
✓ …
```
> [invite] Add method stubs and tests for invite bot + webhooks

- invite/src/github.ts
- invite/src/invitation_record.ts
- invite/src/types.ts
- invite/test/invitation_record.test.ts
```
PASS  test/invitation_record.test.ts
invitation record
recordInvite
✓ records an invite (5ms)
✓ sets `archived = false` (1ms)
getInvites
if no invite record exists for the user
✓ returns an empty list (2ms)
if records exists of invites to the user
✓ returns the invites (1ms)
if only archived invite records exists for the user
✓ returns an empty list (1ms)
archiveInvites
if records exists of any invites to the user
✓ updates the invite records (3ms)
```
> [invite] Add implementation for invitation record methods

- invite/app.ts
- invite/src/github.ts
- invite/test/fixtures/team_membership.active.json
- invite/test/fixtures/team_membership.not_found.json
- invite/test/fixtures/team_membership.pending.json
- invite/test/github.test.ts
Will be used to validate that the comment author is in `ampproject/reviewers-amphtml` (similar to Owners Bot) in order to trigger a macro.
Addresses #687
> [invite] Add team membership check to GitHub API interface

- owners/src/ownership/parser.js
- owners/test/ownership/parser.test.js
The minimatch glob parsing library Owners Bot uses for parsing patterns performs brace-expansion, but only if the braces contain comma-separated patterns. This is not obvious behavior, and has resulted in broken owners rules (see https://github.com/ampproject/amphtml/pull/26899).
Ex. `"{a,b}.js"` becomes `/(a|b)\.js/`
Ex. `"{a}.js"` becomes `/\{a\}\.js/`
This PR identifies rules where there is a single pattern specified within a brace-expansion and rejects the rule, reporting an error. This will block future PRs from submitting rules broken in this way.
/cc @Enriqe
> Report parser error when encountering singleton brace expansion rule patterns

- invite/src/invite_bot.ts
- invite/test/invite_bot.test.ts
When the comment field is empty, GitHub sets it to `null`, which results in an error when trying to parse macros. This has no impact except logging errors since empty comments obviously contain no macros. This PR aborts trying to process a comment if it's empty.
> [invite] Fix error being logged for empty comments

- invite/app.ts
- invite/package-lock.json
The repetitive (long) constructor calls were annoying me, especially with the Probot/Octokit typecast :stuck_out_tongue: 
Addresses https://github.com/ampproject/amp-github-apps/issues/687 and https://github.com/ampproject/meta-tsc/issues/28
> [invite] Add helper to build invite-bot instance from Probot context

- release-calendar/.env.example
- release-calendar/README.md
- release-calendar/package-lock.json
- release-calendar/package.json
- release-calendar/src/server/api-service.ts
- release-calendar/src/server/app.ts
- release-calendar/src/server/entities/release.ts
- release-calendar/test/development-data.ts
- release-calendar/webpack.server.config.js
- Creates `ApiService`, which talks to the database.
- Creates `app`, which starts a router on `localhost:3000` that the client can send requests to for data.
- Bundles it all in `dist/bundle-server.js` using a separate webpack config for the server side.
- Updates npm scripts. To start the API server, run `npm run server`.
- Updates the `src/` directory so it looks like
- (Also fixes some eslint errors).
Closes https://github.com/ampproject/amp-github-apps/issues/722
Closes https://github.com/ampproject/amp-github-apps/issues/737
> [release calendar] Add API server

- bundle-size/package-lock.json
- checklist/package-lock.json
- invite/package-lock.json
- owners/package-lock.json
- package-lock.json
- release-calendar/package-lock.json
- test-status/package-lock.json
This combines dependabot PRs that update acorn incrementally due to a security bug.
Closes https://github.com/ampproject/amp-github-apps/pull/760
Closes https://github.com/ampproject/amp-github-apps/pull/751
Closes https://github.com/ampproject/amp-github-apps/pull/750
Closes https://github.com/ampproject/amp-github-apps/pull/749
Closes https://github.com/ampproject/amp-github-apps/pull/748
> Security fix: update acorn to 7.1.1 (latest)

- bundle-size-chart/package-lock.json
- bundle-size/package-lock.json
- checklist/package-lock.json
- invite/package-lock.json
- owners/package-lock.json
- package-lock.json
- pr-deploy/package-lock.json
- release-calendar/package-lock.json
- test-status/package-lock.json
Update minimist for entire repo due to a security bug.
Closes https://github.com/ampproject/amp-github-apps/pull/759
> Security fix: update minimist to 1.2.5 (latest)

- owners/src/ownership/owners_check.js
- owners/test/ownership/owners_check.test.js
Truncates output text of check-runs to the API limit of 65535 characters. Result is pretty abrupt "…[TRUNCATED]" and it's possible it could screw up formatting, such as by truncating within an italic block or something, but since this case is so rare I think that's good enough.
> Truncate text that is over the GitHub API limit for CheckRun output

- bundle-size/package-lock.json
- checklist/package-lock.json
- invite/package-lock.json
- owners/package-lock.json
- pr-deploy/package-lock.json
- pr-deploy/src/github.ts
- release-calendar/package-lock.json
- test-status/package-lock.json
`kind-of` needs to be upgraded to 6.0.3 to fix a security vulnerability. Easiest way is to delete package-lock.json files where it's found, and run `npm install`.
> 🌿Freshen up package lock files to fix `kind-of` security vulnerability

- error-issue/index.ts
- error-issue/package-lock.json
- error-issue/package.json
- error-issue/src/blame_finder.stub.ts
- error-issue/src/bot.ts
- error-issue/src/issue_builder.stub.ts
- error-issue/src/rate_limited_graphql.stub.ts
- error-issue/src/types.ts
- error-issue/test/bot.test.ts
Part of https://github.com/ampproject/error-tracker/issues/112
Uses stubbed implementations of the BlameFinder (https://github.com/ampproject/amp-github-apps/pull/779) and IsssueBuilder (https://github.com/ampproject/amp-github-apps/pull/780) while they are under review.
Easiest to follow commit-by-commit
Top-down view:
```
PASS  test/bot.test.ts
ErrorIssueBot
buildErrorIssue
✓ determines blame for the stacktrace (20ms)
✓ builds the issue to be created (14ms)
report
✓ creates an error issue (36ms)
✓ propagates the error when the API call fails (10ms)
------------------------------|---------|----------|---------|---------|-------------------
File                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```
> [error-issue] Creates error-issue bot to glue blame finding and issue creation

- release-calendar/src/client/components/App.tsx
- release-calendar/src/client/components/Calendar.tsx
- release-calendar/src/client/components/ChannelTable.tsx
- release-calendar/src/client/models/release-event.ts
This PR focuses on handling when rows in the `ChannelTable` are checked and sending those selected channels up to the root `App` and back down to the `Calendar`. 
Included:
-  `channels`, an array of selected `Channel`s, which is a state structure in `App` and a prop in `ChannelTable` and `Calendar`.
- the function `handleSelectedChannel` in `App` to handle adding a new channel to the `channels` array or removing a channel that is getting deselected.
- the transfer of `ApiService` to `Calendar` from `App` so that `events`, the `Map<Channel, EventSourceInput>`, can be isolated to only the component that needs it, `Calendar`. 
- the restructuring of `getEvents` to return a `Map<Channel, EventSourceInput>`instead of the more rigid array of `EventSourceInput[]`
> [release-calendar] Event Handling

- error-issue/src/issue_builder.ts
- error-issue/test/fixtures/created-issue.md
- error-issue/test/issue_builder.test.ts
Without it, the link is interpreted as a relative path and doesn't work.
> [error-issue] (XS) Add "http://" to link URL

- owners/index.js
- owners/src/api/github.js
- owners/src/notifier.js
- owners/test/api/github.test.js
- owners/test/notifier.test.js
App-authenticated comments appear to come from the app user (ie. `amp-owners-bot`) but can't tag teams. The workaround is doing a fake update to the comment with a user-authenticated client, which enables the @ mention but leaves the comment author as the app name.
> [owners] Fix team @ mentions

- error-issue/index.ts
- error-issue/package.json
- error-issue/src/stackdriver_api.ts
With this PR, error issues created by the bot can/will be automatically linked to the originating error in error tracking. It also updates the `error-issue` endpoint to accept just an error ID, in which case it will fetch the remaining details from Stackdriver.
If you add the following code as a bookmarklet:
```
javascript:(function()%7Bconst %7BerrorId%7D %3D location.pathname.match(%2F%5C%2Ferrors%5C%2F(%3F<errorId>%5B%5E%5C%2F%3F%5D%2B)%2F).groups%3Bwindow.open(%60https%3A%2F%2Fus-central1-amp-error-issue-bot.cloudfunctions.net%2Ferror-issue%3FerrorId%3D%24%7BerrorId%7D%26linkIssue%3D1%60%2C'_blank')%7D)()
````
clicking it while viewing any error in AMP Error Reporting will create, link, and redirect to the new GitHub issue.
> [error-issue] Add auto-linking of created issue to GCP error

- release-calendar/src/client/api-service.ts
- release-calendar/src/client/components/Calendar.tsx
- release-calendar/src/client/models/release-event.ts
- release-calendar/src/client/models/view-models.ts
- release-calendar/src/client/stylesheets/_base.scss
- release-calendar/src/client/stylesheets/channelTable.scss
- release-calendar/src/server/repository-service.ts
- release-calendar/src/types.ts
Why we need a .getReleases() : getReleases will be used by the client side to query for the all the releases to be displayed on in the `Calendar`.
Included: 
- Removal of the `Release` type on the Client side. Before the data to be displayed on the `Calender` was being transformed from what the server side version of the `Release`type into the client side version of the `Release` type and then to `EventInput`. Now data will go straight from client side `Release` to `EventInput.`
- Addition of an end date to EventInput so that calendar events have a duration
- Addition of a server side `getReleases()` query that groups promotions by channel and then orders by date so to allow for the end date to be calculated later on the server side.
- Change of of a client side `getAllReleasesEvents()` …
> [release-calendar] Add api call getReleases for all releases

- release-calendar/src/server/repository-service.ts
The bug: 
```
Object.keys(Channel).map((channel) => 
return this.promotionRepository
.createQueryBuilder('promotion')
.where('promotion.channel = :channel', {channel})
```
**channel** isn't being recognized correctly. Queries are only being recognized if the channel does not include a hyphen :(
> [release-calendar] 🐛 Remove getCurrentReleases bug 🐛

- release-calendar/src/client/api-service.ts
- release-calendar/src/client/components/App.tsx
- release-calendar/src/client/components/Calendar.tsx
- release-calendar/src/client/components/ChannelTable.tsx
- release-calendar/src/client/models/release-event.ts
- release-calendar/src/client/models/view-models.ts
- release-calendar/src/server/app.ts
- release-calendar/src/server/repository-service.ts
Why we need a ` getRelease(requestedRelease: string)`: getRelease will be used by the client side to query for all the promotions a single release has underwent so that they can be displayed on the `Calender.`
This is what one example release looks like as it flows from Nightly to LTS.
Included:
- Addition of a server side getRelease() query that joins the promotions and release tables and selects the requested release and all of its promotions (promotions in descending order)
- Addition of the `Release` string that will live in the `App` state but also in the props of `Calendar`
- Event handling associated with clicking on a `rtv-button`
- Addition of `getSingleReleaseEvents()` which converts the `ReleaseEventInputs` into `EventSourceInput[]` to be read by the calendar.
TODO: Toggle …
> [release-calendar] Add getRelease()

- onduty/cloud_build.yaml
- onduty/index.ts
- onduty/package-lock.json
- onduty/package.json
- onduty/redacted.env
- onduty/src/bot.ts
- onduty/test/e2e.test.ts
- onduty/test/jest-preload.ts
- onduty/types/index.d.ts
I've confirmed this is functioning as expected on my test org.
```
PASS  test/e2e.test.ts
On-Duty Bot
✓ refreshes GitHub teams with new rotations (1048ms)
✓ returns 401 Unauthorized for an invalid token (2ms)
✓ returns 500 Internal Server Error if something goes wrong (7ms)
------------|---------|----------|---------|---------|-------------------
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------|---------|----------|---------|---------|-------------------
All files   |     100 |      100 |     100 |     100 |                   
onduty     |     100 |      100 |     100 |     100 |                   
index.ts  |     100 |      100 |     100 |     100 |                   
onduty/src |     100 |      100 |     100 |     100 |                   
bot.ts …
```
> [onduty] Add handlers to receive rotation updates

- onduty/redacted.env
- onduty/src/bot.ts
- onduty/test/bot.test.ts
- onduty/test/jest-preload.ts
> [onduty] Never remove bot user from rotation teams

- onduty/index.ts
**Facepalm**
Because of this, the new `BOT_USERNAME` isn't initialized properly
> [onduty] (1 line) Configure dotenv before importing bot

- test-status/api.js
- test-status/test/api.test.js
Fixes #783
Tag-along changes:
* the `travisJobUrl` field is always included, no need to do a special-case handler for when it's missing
* overdue lint fixes
//cc @jridgewell
> [test-status] Add Travis URL to status text of passed tests suites

- error-issue/package.json
- error-issue/src/issue_builder.ts
- error-issue/test/fixtures/created-issue.md
- error-issue/test/issue_builder.test.ts
- error-issue/test/rate_limited_graphql.test.ts
```
Error: null is not an object (evaluating 'b.acceleration.x')
at x (https://raw.githubusercontent.com/ampproject/amphtml/2004030010070/extensions/amp-delight-player/0.1/amp-delight-player.js:421:13)
at event (https://raw.githubusercontent.com/ampproject/amphtml/2004030010070/src/event-helper-listen.js:58:27)
```
<pre><code>
Error: null is not an object (evaluating 'b.acceleration.x')
at x (<a href="https://github.com/ampproject/amphtml/blob/2004030010070/extensions/amp-delight-player/0.1/amp-delight-player.js#L421">extensions/amp-delight-player/0.1/amp-delight-player.js:421</a>:13)
at event (<a href="https://github.com/ampproject/amphtml/blob/2004030010070/src/event-helper-listen.js#L58">src/event-helper-listen.js:58</a>:27)
</code></pre>
> Linkize stack traces to the relevant file

- error-issue/index.ts
- error-issue/package-lock.json
- error-issue/package.json
- error-issue/src/utils.ts
- error-issue/test/utils.test.ts
Fixes three bugs:
1. `seenInVersions` list is incorrectly URL-encoded; should be encoded as a repeated query param, instead is encoded as comma-separate list.
- Fixed by using `querystring.stringify` library
2. Stacktraces with a different format fail parsing
- Fixed by adding a fallback regex check
3. Query parameter `seenInVersions` is expected as an array, but when it's a one-item array it gets parsed as a string
- Fixed by wrapping in an array
> [error-issue] Fix bugs/weird quirks in URL encoding

- error-issue/package.json
- error-issue/src/error_monitor.ts
- error-issue/src/issue_builder.ts
- error-issue/test/fixtures/created-issue.md
- error-issue/test/issue_builder.test.ts
Because of the `<pre>`, the newline is actually rendered now.
Before: 
After:
> [error-issue] Remove extra newline in stacktrace code block

- error-issue/index.ts
- error-issue/src/error_monitor.ts
- error-issue/test/error_monitor.test.ts
This PR:
- allows error monitor frequency thresholds to be overridden
- provides a `threshold` query param to do so for error list views
- computes the resulting "normalized" threshold (ie. 50/day in Nightly --> 9800/day across all services)
Usage (UI in prototype):
> [error-issue] Allow for overriding frequency threshold

- owners/src/notifier.js
- owners/test/notifier.test.js
Necessitated by bugs/quirks in how GitHub handles thread notifications when @ mentioned users add reviews. See issue thread for details.
Closes https://github.com/ampproject/amphtml/issues/28253
/cc @gmajoulet
> [owners] Don't exclude reviewers from notification comments

- error-issue/cloud_build.yaml
- error-issue/index.ts
- error-issue/static/error-list.html
- error-issue/types/error-issue-bot.d.ts
Currently, the "Create Issue" links include all the error report fields: stacktrace, seen versions, frequency, etc. This PR simplifies the link to include only the error ID, allowing the backend to fetch the most up-to-date stats when creating the issue
> [error-issue] Simplify issue creation URL

- owners/src/reviewer_selection.js
- owners/test/reviewer_selection.test.js
Addresses a subtle bug seen in reviewer assignment on https://github.com/ampproject/amphtml/pull/28489
A key step in prioritizing reviewer selection involves finding the deepest owners rules that apply to each file in a PR. In the case of the above PR, `validator/java/OWNERS` includes two users who are not members of `reviewers-amphtml`. In this case, the algorithm tries to satisfy that rule, then later on when the non-reviewers are eliminated, it has no reviewer suggestions.
This PR adds an automatic backoff to that step of the algorithm. When it fails to find any potential reviewers to satisfy the deepest layer of owners rules, it climbs the tree and tries to satisfy the next-deepest set of rules.
> Fix handling of leaf nodes owned by non-reviewers

- error-issue/src/stackdriver_api.ts
Since Experiemnt A was turned down, there are no longer errors under the "Experiments" bucket, so that query turns up empty. Because Stackdriver responds with no value, instead of an empty array, this would error when trying to call `.map`. This initializes the field to an empty array.
> [error-issue] Handle empty list repsonse from stackdriver

- error-issue/app.ts
- error-issue/app.yaml
- error-issue/package-lock.json
- error-issue/package.json
- error-issue/redacted.env
- error-issue/src/error_monitor.ts
- error-issue/test/error_monitor.test.ts
Since there are multiple endpoints and because server-side caching may become useful for Stackdriver, this makes more sense as an App Engine app.
Updates to README and cloud_build.yaml will be included in a follow-up PR
> [error-issue] Migrate error monitor to App Engine

- error-issue/app.yaml
- error-issue/package-lock.json
- error-issue/package.json
- error-issue/src/stackdriver_api.ts
Adds a 1-hour cache to the API requests listing error groups. Allows users to quickly jump between different buckets (Production, 1%, Nightly, etc.) without re-issuing API queries each time.
> [error-issue] Cache error list API requests in Stackdriver interface

- bundle-size/setup-db.js
`table.string` produces a `varchar(255)` column, whereas `table.text` produces a `text` column. We need `text` for the markdown field, in case it's longer than 255 characters.
* https://www.postgresql.org/docs/9.5/datatype-character.html
* http://knexjs.org/#Schema-text
> [bundle-size] Change type of report_markdown from string to text

- bundle-size/api.js
Because one newline after a markdown list just continues the same list-item, but two newlines start a new paragraph
> [bundle-size] [typo] add a newline after the markdown report list

- error-monitoring/src/stackdriver_api.ts
Because of the caching, the list doesn't know to refresh when an issue gets created. This PR causes the Stackdriver interface to flush its cache whenever it updates an error group.
> [error-monitoring] Flush Stackdriver cache when triggering updates

- error-monitoring/src/blame_finder.ts
- error-monitoring/test/blame_finder.test.ts
- error-monitoring/test/fixtures/2004030010070/extensions-amp-delight-player-0_1-amp-delight-player_js.json
- error-monitoring/test/fixtures/2004030010070/extensions-amp-next-page-1_0-service_js.json
- error-monitoring/test/fixtures/2004030010070/src-event-helper-listen_js.json
- error-monitoring/test/fixtures/2004172112280/extensions-amp-base-carousel-0_1-dimensions_js.json
- error-monitoring/test/fixtures/master/src-log_js.json
- error-monitoring/types/error-monitoring.d.ts
Fixes #903
Originally, fetched the commit message and parsed out the PR number to simplify the query/reduce the query "cost" for the GraphQL rate limit, but that failed whenever the commit message headline was too long and got truncated. This adds a join against the `associatedPullRequests` connection, which should directly provide the PR number when available.
> [error-monitoring] Use `associatedPullRequests` field in GraphQL query

- test-case-reporting/types/test-case-reporting.d.ts
/cc @rcebulko 
Works toward #884.
Sample of the test result report JSON generated when we run `gulp unit`
```json
"summary": {
"success": 10879,
"failed": 21,
"skipped": 195,
"error": false,
"disconnected": false,
"exitCode": 1
},
"browsers": [
{
"browser": {
"id": "52060",
"fullName": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36",
"name": "Chrome 83.0.4103.97 (Linux x86_64)",
"state": "DISCONNECTED",
"lastResult": {
"startTime": 1592249357208,
"total": 11095,
"success": 10879,
"failed": 21,
"skipped": 195,
"totalTime": 813363,
"netTime": 275545,
"error": false,
"disconnected": false
},
"disconnectsCount": 0,
"noActivityTimeout": 120000,
"disconnectDelay": 120000
},
"errors": [],
"results": [
{
"id": "",
"description": …
```
> [test-case-reporting] Add types for Travis test reports

- error-monitoring/app.ts
- error-monitoring/cron.yaml
- error-monitoring/index.ts
- error-monitoring/redacted.env
- error-monitoring/src/bot.ts
- error-monitoring/test/bot.test.ts
This PR:
- allows us to use a dedicated "error-reports" repository to track issues separately from user-created issues, per request of @kristoferbaxter to reduce issue noise for the UI WG
- defines cron endpoints to automatically file issues each morning for newly detected frequent errors in the wild
> [error-monitoring] Allow for reporting errors to a separate repo + cron endpoint to do so

- error-monitoring/index.ts
- error-monitoring/src/error_monitor.ts
- error-monitoring/static/error-list.html
Also renames a couple functions
First piece of #931
> [error-monitoring] Add instructions for manually linking duplicate errors

- error-monitoring/app.ts
- error-monitoring/index.ts
- error-monitoring/static/error-list.html
This PR adds a simple button/input allowing the release on-duty to link an existing tracking issue to a duplicate error (common when different browsers/module builds report the same error with varying stacktraces). Includes an endpoint which links the tracking issue then returns to the error list.
Before:
After:
> [error-monitoring] Add option to link existing GitHub issue to errors

- test-case-reporting/src/setup_db.ts
Foreign key `test_runs.test_case_id` had a type mismatch.
> [test-case-reporting] Fix bad foreign key type

- test-case-reporting/src/setup_db.ts
- test-case-reporting/src/test_case_stats.ts
- test-case-reporting/test/testing_utils.ts
Note: The query here is somewhat complex (uses a few subqueries), but this allows PG to do all the work rather than shipping it back and forth to JS. This optimization is relevant given the massive scale (ie. >10k test cases * 100 jobs)
> [test-case-reporting] Compute pass/fail/skip/error stats for test cases

- error-monitoring/index.ts
Threshold determines which repo to link to when providing an issue number. numbers under 10k are clearly new ones from `ampproject/error-reporting`, PR numbers over that belong to `ampproject/amphtml`. First attempt was 20k, which failed when linking really old issues in the 17000s
> [error-monitoring] Lower threshold for legacy issue repo

- test-case-reporting/app.ts
- test-case-reporting/cloud_build.yaml
- test-case-reporting/cron.yaml
- test-case-reporting/src/setup_db.ts
- test-case-reporting/src/test_case_stats.ts
- test-case-reporting/src/test_result_record.ts
- test-case-reporting/static/css/custom.css
- test-case-reporting/static/test-case-list.html
- test-case-reporting/static/test-run-list.html
- test-case-reporting/test/test_result_record.test.ts
- test-case-reporting/types/test-case-reporting.d.ts
This PR includes a smattering of fixes and small tweaks. Many of these tweaks are only to display extra info (pass/fail stats, Travis links, etc) in the front-end. The current front-end is a bare minimum display of simple info, done this way so Ricardo would have a simple UI to present, but the plan is to build a proper front-end using the JSON endpoints in the server. 
TL;DR - Changes in HTML files and the request handlers in `app.js` are not intended to be perfect, just minimally usable for the purposes of identifying broken/flaky tests and navigating around the app.
This PR:
- fixes the cron configuration and updates it to run frequently-er
- extends the timeout for Cloud Build (so builds don't fail because `gcloud app deploy` takes forever)
- add deployment of cron changes to Cloud …
> [test-case-reporting] Misc. fixes and updates to make app useful

- bundle-size-chart/cloud_build.yaml
- bundle-size/cloud_build.yaml
- checklist/cloud_build.yaml
- invite/cloud_build.yaml
- onduty/cloud_build.yaml
- test-status/cloud_build.yaml
Some of these projects fail to deploy because the default 10m timeout is too short
> [build-system] Increase gcloud deploy timeout to 20 minutes for all projects

- project-metrics/metrics_service/apis/travis.py
This is in anticipation of the mandatory [migration from `travis-ci.org` to `travis-ci.com`](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository) that was announced in 2018, but is being enforced soon. AMP is going to do this migration later today. We'll need to merge the PR after the migration is in place. Since this change is not in the critical path for development, it can be reviewed and merged when convenient.
Companion PR to https://github.com/ampproject/amphtml/pull/30846
> Update Travis API URL from `.org` to `.com`

- error-monitoring/index.ts
- error-monitoring/src/bot.ts
- error-monitoring/test/bot.test.ts
Right now, clicking this button links the existing GitHub issue to a duplicate Stackdriver error report. This has become extremely common as a result of ESM changing the stacktraces (and grouping) of pretty much every production error. Currently, there's no way to see all the errors that are related to a certain issue. This PR causes the bot to auto-comment on the existing GitHub issue, linking to the new duplicate.
> [error-monitoring] Comment on existing error issues when a duplicate error is linked

- test-status/README.md
- test-status/api.js
- test-status/test/api.test.js
**PR highlights:**
- Makes test status reporting CI agnostic
- Removes the check for IP addresses (wasn't used for Travis, and [won't be used](https://support.circleci.com/hc/en-us/articles/115014372807-IP-Address-ranges-for-safelisting-Do-you-have-static-IP-addresses-available-) for CircleCI)
- Removes tests for IP address checks
With this, test status reporting should continue to work on Travis, and also work on other CI services.
Fixes #1111
> Make test status reporting CI agnostic

- owners/README.md
Part of the move away from Travis. For owners bot, there appears to be only this one spot in the documentation that needs an update. (Anything else?)
> Update owners-bot documentation to be CI-agnostic

- DEPLOYMENT.md
- bundle-size-chart/package.json
- bundle-size/package.json
- checklist/package.json
- error-monitoring/package.json
- invite/package.json
- onduty/package.json
- owners/package.json
- test-case-reporting/package.json
- test-status/package.json
We use `date --utc` to generate a timestamp while creating a deployment tag for our apps. Turns out that Linux supports `date --utc` and the shorter form `date -u`, but macOS only supports the latter.
This PR makes deployment steps work across both Posix platforms.
> Make deployment work across Posix platforms

- bundle-size-chart/package-lock.json
- owners/package-lock.json
- pr-deploy/package-lock.json
Details of dependabot alert
```
GHSA-r92x-f52r-x54g
high severity
Vulnerable versions: < 0.14.2
Patched version: 0.14.2
This issue may lead to a denial of service.
```
> Upgrade date-and-time to 0.14.2 to fix dependabot alert

- owners/src/ownership/tree.js
- owners/test/ownership/tree.test.js
The source of this error is unclear (I suspect it's some undocumented change it GitHub APIs response), but this will ensure that errors in owners tree creation don't bubble up and take down the bot.
/cc @Enriqe
> Catch error when an OWNERS file has an invalid path

- pr-deploy/README.md
- pr-deploy/src/app.ts
- pr-deploy/src/github.ts
- pr-deploy/src/zipper.ts
- pr-deploy/test/app.test.ts
- Updates all internal implementation to be CI-agnostic
- Adds a HTTP post handler for `/cibuilds/` (`/travisbuilds` will be cleaned up after `amphtml` stops using it)
I'm guessing we cannot merge this PR until the storage location used by CI is updated (coming up separately). Meanwhile, sending this out for preliminary review.
Fixes #1110
> Make pr-deploy bot CI agnostic

- error-monitoring/cron.yaml
- error-monitoring/index.ts
- error-monitoring/src/bot.ts
- error-monitoring/src/issue_builder.ts
- error-monitoring/test/fixtures/created-issue.md
- error-monitoring/test/issue_builder.test.ts
Originally the issue builder wrote a PR as `#1337`, however now that issues are reported into a separate repo, there's no linking. This updates the issue builder to create full links for referenced PRs in the stacktrace blame.
It also disables cron jobs to autofile issues; that shouldn't have been on, and I'm not sure why I turned it on.
> [error-monitoring] link to PRs in created issues

- test-case-reporting/app.ts
- test-case-reporting/types/test-case-reporting.d.ts
Allows CI to report `jobId` and `buildId` immediately while backend migrations are queued. Part of https://github.com/ampproject/amphtml/issues/31996
> [test-case-reporting] Accept job/build ID fields from CI

- pr-deploy/README.md
- pr-deploy/src/app.ts
- pr-deploy/src/github.ts
- pr-deploy/src/zipper.ts
- pr-deploy/test/app.test.ts
With the move to CircleCI, build identifiers are no longer guaranteed to be numeric. This PR makes them strings so any kind of identifier can be passed in.
**Side note:** Binary filenames uploaded during CI were renamed to `amp_nomodule_*.zip` and `amp_module_*.zip` in https://github.com/ampproject/amphtml/pull/31940. We'll need to re-deploy #1141 + this PR so the paths can match up again.
Fixes #1110
> Make PR deploy bot accept non-numeric build identifiers

- pr-deploy/src/github.ts
The Github check for the PR deploy bot reports a build identifier in the following formats:
```sh
CI build ID: 12345
CI build ID: aaaaaaaa-bbbb-cccc-ddddddddddddddddd
```
In #1196, we removed the code that converted the build ID to a number (desired change), and also removed the code that eliminated the `CI build ID: ` prefix (undesired change). (See [this](https://github.com/ampproject/amp-github-apps/pull/1196/files#diff-87ebe063534f5df9d5ed5227bf7a7112fa26925410573f643c17ad1eda0b5001L211) line.)
This PR restores the prefix removal bit.
> Fix PR Deploy bot build ID extraction

- pr-deploy/README.md
- pr-deploy/package.json
- pr-deploy/src/app.ts
- pr-deploy/src/github.ts
- pr-deploy/src/zipper.ts
- pr-deploy/test/app.test.ts
This PR updates the PR deploy app to use the commit SHA as the binary file suffix.
Companion to https://github.com/ampproject/amphtml/pull/32083.
> Switch PR Deploy unique identifier from build ID to commit SHA

- error-monitoring/cloud_build.yaml
- error-monitoring/src/issue_builder.ts
- error-monitoring/test/fixtures/created-issue.md
- error-monitoring/test/issue_builder.test.ts
Duplicate error issues have been getting filed, and I'm not sure why. I tried revoking the old access token and this re-deploys with a new one, in case some vestige was running jobs somehow and filing error reports. Also, fixes a typo in PR urls.
> [error-monitoring] Replace GitHub Access Token and fix URL typo

- bundle-size/api.js
- bundle-size/test/api.test.js
This will help debug corner cases like older PR branches (with newer commits on `master`) and unexpected bundle-size changes. Extra markdown will look like this:
**Head commit:** 0cbb639
**Base commit:** 0d927f7
**Code changes:** https://github.com/ampproject/amp-github-apps/compare/0d927f7..0cbb639
> Show commit info in bundle-size check-run details

- release-calendar/README.md
- release-calendar/package.json
- release-calendar/redacted.env
- release-calendar/src/client/api-service.ts
- release-calendar/src/client/components/Calendar.tsx
- release-calendar/src/server/repository-service.ts
- release-calendar/webpack.client.dev.config.js
- release-calendar/webpack.client.prod.config.js
- Fix client side api service that wasn't fetching data from server
- Fix SQL query that was throwing an error on prod but not dev
- Add instructions to README to mimic prod sql instance
- Change client port to mimic [App Engine entrypoint](https://cloud.google.com/appengine/docs/standard/nodejs/config/appref) setting
Fixes ampproject/amphtml#32791
> [release calendar] Fix local dev and ChannelTable sql query

- bundle-size/api.js
- bundle-size/test/api.test.js
Uses the [new `mergeSha` field](https://github.com/ampproject/amphtml/pull/33165/files#diff-c141453bcbdbe03ca8414e5b4d425c5b7323e43d524b614455ce13770633509eR191), which resolves https://github.com/ampproject/amphtml/pull/33165#issuecomment-794642367.
> bundle-size: Use mergeSha when showing code changes

- test-status/db.js
- test-status/setup-db.js
* I already changed the database type directly to fix the integer overflow error from the db engine
* knex [returns `bigint`s as strings](http://knexjs.org/#Schema-bigInteger) because it might overflow the safe JavaScript max number value, but we can probably safely assume it won't go over [9,007,199,254,740,991](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), so explicitly cast all of them to Numbers after the db returns
> [test-status] Change checkRunId's data type from integer to bigint

- test-case-reporting/static/test-run-list.html
In #1194, I attempted transplant surgery on the test case reporting backend to make its database CI agnostic for the switch from Travis to CircleCI. This turned out to be a bad idea due to https://github.com/ampproject/amp-github-apps/pull/1194#pullrequestreview-569405440, so the effort was abandoned.
This PR applies a band-aid to the top-level HTML report page to make the links read "CircleCI" instead of "Travis". This should fix the visible UI until we think it's worth the engineering effort to go in and update the backend by adding a new CI service type.
Related PR: https://github.com/ampproject/amphtml/pull/33389
Closes #1113 (can reopen if / when we think it's worth a bigger rewrite)
> Rename links in test reporting page from Travis to CircleCI

- bundle-size/common.js
- bundle-size/setup-db.js
Same as #1242 but for bundle-size
> * I already changed the database type directly to fix the integer overflow error from the db engine
> * knex [returns `bigint`s as strings](http://knexjs.org/#Schema-bigInteger) because it might overflow the safe JavaScript max number value, but we can probably safely assume it won't go over [9,007,199,254,740,991](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), so explicitly cast all of them to Numbers after the db returns
> [bundle-size] Change checkRunId's data type from integer to bigint

- onduty/README.md
- onduty/index.ts
- onduty/redacted.env
- onduty/test/bot.test.ts
- onduty/test/e2e.test.ts
- onduty/test/jest-preload.ts
- onduty/types/index.d.ts
This is something we've been meaning to do for a while.
**Companion PR:** https://github.com/ampproject/amphtml/pull/33465
**Next steps:**
> Replace all mentions of `build cop` with `build on-duty`

- .github/workflows/pr-check.yaml
- build-system/git.js
- checklist/README.md
- error-monitoring/README.md
- invite/README.md
- onduty/README.md
- owners/src/repo/local_repo.js
- owners/test/repo/local_repo.test.js
- test-case-reporting/README.md
- test-case-reporting/test/e2e.test.ts
- test-status/api.js
- Sets the stage to change the default branch of `amp-github-apps` to `main`
- The only instances of `master` that will remain in this repo are links to [`meta`](https://github.com/ampproject/meta/tree/master), [`amphtml-build-artifacts`](https://github.com/ampproject/amphtml-build-artifacts/tree/master), [`amphtml`](https://github.com/ampproject/amphtml/tree/master), and [`error-tracker`](https://github.com/ampproject/error-tracker/tree/master). They'll need to be updated separately.
**Note:** Looks like `prettier` auto-formatting kicked in for the `.md` files I updated. I'm going to leave those changes in.
**Next steps:** Soon after this PR is merged, we can rename the default branch to `main`. After review, I'll coordinate this action manually. This will serve as a …
> Prepare to rename the default branch of `amp-github-apps` to `main`

- bundle-size/api.js
- bundle-size/package-lock.json
- bundle-size/test/api.test.js
Was going to make a feature request, but figured it would be easier to just offer the change as a PR. Sorts bundle-size output by delta, so it's easy to scan the list for the files with the largest/smallest relative changes.
> Sort bundle size output by delta instead of binary

- pr-deploy/package.json
Turns out that `devDependencies` are [deleted before GCP saves the Docker image](https://cloud.google.com/appengine/docs/standard/nodejs/specifying-dependencies) that will be used for deploying the app. This PR attempts to fix this so that the [app gets compiled in that step](https://cloud.google.com/appengine/docs/standard/nodejs/running-custom-build-step), and `npm start` literally only starts the aleady-compiled app
> [pr-deploy] Add gcp-build step to package.json

- pr-deploy/src/app.ts
- pr-deploy/src/github.ts
* the description field for a GitHub check's action can be at most 40 characters, shorten it
* split up the handlers for success/errored/skipped
* move common code to middleware
* it's no longer necessary to explicitly cast Octokit instances from Probot
> [pr-deploy] Code cleanup and fix description-too-long error

- test-case-reporting/static/index.html
In https://github.com/ampproject/amp-github-apps/pull/1258 I changed the default landing page of the test-case-reporting page to `index.html`. Somehow throughout the process that file didn't end up as part of the commit.
Hmm...
I swear it works now:
> Fix test-case-reporting landing page.

- owners/src/api/github.js
- owners/src/ownership/parser.js
- owners/src/repo/virtual_repo.js
- owners/test/api/github.test.js
- owners/test/repo/virtual_repo.test.js
Currently the bot uses the GitHub Search API + file SHAs to identify new/changed OWNERS files. The search API seems to be returning incomplete results, meaning some files never get seen with updated SHAs and can get stale. This PR:
- causes the virtual repo to manually re-fetch any OWNERS files it thinks exist, but weren't present in search results
- removes OWNERS files from the in-memory cache if attempting fetching them returns an error
> Improve handling of new and removed OWNERS files in cache

- owners/OWNERS.example
- owners/src/ownership/parser.js
- owners/src/ownership/schema.json
- owners/test/ownership/parser.test.js
- owners/test/reviewer_selection.test.js
Closes https://github.com/ampproject/amp-github-apps/issues/1283
Requires an update to amphtml's root OWNERS file, but this should not fail any PRs on that repo in the interim unless they trigger OWNERS build target. Will require pushing an updated deploy tag to trigger a build.
Before: `reviewerTeam` allowed only in repo root `OWNERS` file, must be a string representing a team
Now: `reviewerPool` allowed only in repo root `OWNERShi file, must be an array of strings representing teams or usernames
> [owners] Support `reviewerPool` of users and/or teams in place of `reviewerTeam` property

- owners/src/cache/compound_cache.js
- owners/src/repo/virtual_repo.js
A recent change to the owners cache introduced an accidental double-call to a helper that prepends the repo root to a filepath, resulting in the cache system trying to delete a nonexistent file at `amphtml/amphtml/...` and crashing each time the bot tried to refresh. This PR fixes that, and wraps the cache so errors are logged but do not blow up tree parsing/refreshing.
> [owners] Fix double-call to path helper

- owners/OWNERS.example
- owners/src/ownership/schema.json
- owners/test/ownership/parser.test.js
- Add a new `Bot` definition to `schema.json` (same as `User`, but ends in `[bot]`)
- Update `OWNERS.example`
- Update tests in `parser.test.js`
- Bonus: Fix outdated WG name and lines longer than 80 chars in `OWNERS.example`
Required by https://github.com/ampproject/amphtml/pull/34211
> [owners] Allow bots to be listed in `reviewerPool`

- build-system/ci.js
- build-system/git.js
During build target computation, we look at the set of files changed by a PR when compared with the common ancestor commit with the `main` branch. On Travis, it was sufficient to use `main`, but on GH actions, we need to use `origin/main`.
For evidence, see this screenshot from an `amphtml` GH Actions [build](https://github.com/ampproject/amphtml/runs/2503804538?check_suite_focus=true#step:4:23):
Addresses https://github.com/ampproject/amp-github-apps/pull/1284#issuecomment-831404707
> Update main branch name used during CI

- release-calendar/package-lock.json
An automated email prompted me to run `npm audit` on release calendar and I was presented with a huge number of security vulnerabilities most of which could be automatically patched. 
Before:
[release-calendar-audit.txt](https://github.com/ampproject/amp-github-apps/files/6436959/release-calendar-audit.txt)
After:
> update release-calendar packages to resolve vulnerabilities

- test-case-reporting/package-lock.json
Running `npm audit` on the test-case-reporting package showed a lot of automatically patchable vulnerabilities.e
Before:
After:
> ♻️  fix vulnerabilities in test-case-reporting

- bundle-size/webhooks.js
1. We now check multiple bundles, not just one (`v0`).
2. We check both `.mjs` and `.js`
> Change wording of bundle size blurb

- renovate.json
- Update dependency dashboard link to https://github.com/ampproject/amp-github-apps/issues/1338
- Enable auto-review + auto-merge for PRs that pass all CI checks
- Also group major version upgrades (there are way [too many](https://github.com/ampproject/amp-github-apps/issues/1338#issue-910538348) to do individually)
- Update assignees
With this, the bulk of upgrades that pass CI checks will get auto-reviewed and auto-merged.
> Enable auto-merging of upgrade PRs if CI is green

- renovate.json
This PR temporarily sets the renovate setting `rebaseWhen` to `never` so there's less noise while the [initial backlog](https://github.com/ampproject/amp-github-apps/pulls?q=is%3Apr+is%3Aopen+author%3Aapp%2Frenovate+sort%3Aupdated-desc) of updates is cleared. If an upgrade PR needs accompanying code changes, the PR branch will have to be manually rebased after the code is fixed.
Once we're caught up, it may be possible to restore `rebsaeWhen` to the default of `conflicted` and still avoid PR noise. Can revisit this bit later.
**Reference:** https://docs.renovatebot.com/configuration-options/#rebasewhen
> Disable auto-rebasing of update PRs

- build-system/pr-check.js
- build-system/utils.js
- package.json
- For repo-wide linting, directly call `npm run lint` for clarity
- De-dupe the various start / stop messages to make CI logs easier to read
**Screenshot:** ([link](https://github.com/ampproject/amp-github-apps/runs/2766824614?check_suite_focus=true#step:4:23))
Addresses https://github.com/ampproject/amp-github-apps/pull/1369#discussion_r646749369
> Don't hide repo-wide lint behind test during CI

- release-calendar/test/setup.ts
The release calendar setup script reads the wrong environment variable when setting up the database.
> [release-calendar] fix issue in release calendar setup

- release-calendar/src/server/app.ts
The client cannot currently retrieve information from the backend due to an issue with the cors policy which assumes the client is running on `CLIENT_PORT`.
> [release-calendar] Fix CORS issue preventing the client from communicating with the server

- README.md
- build-system/build-targets.js
- renovate.json
- webhook-pubsub-publisher/.eslintrc.js
- webhook-pubsub-publisher/.gcloudignore
- webhook-pubsub-publisher/.gitignore
- webhook-pubsub-publisher/README.md
- webhook-pubsub-publisher/cloud_build.yaml
- webhook-pubsub-publisher/package-lock.json
- webhook-pubsub-publisher/package.json
- webhook-pubsub-publisher/redacted.env
- webhook-pubsub-publisher/src/app.ts
- webhook-pubsub-publisher/src/index.ts
- webhook-pubsub-publisher/test/app.test.ts
- webhook-pubsub-publisher/test/tsconfig.json
- webhook-pubsub-publisher/tsconfig.json
- webhook-pubsub-publisher/types/probot__serverless-gcf.d.ts
The intention is to install this app on the amphtml repository and listen to `push` webhook events, then a google-internal app will subscribe to the Pub/Sub topic and synchronize any changes to the [client-side experiment config](https://github.com/ampproject/amphtml/issues/34013) file with the CDN - this way the google-internal part is kept to a minimum, since any CDN can listen to the same Pub/Sub topic and perform a similar sync
> Add a new GitHub app that publishes any webhook it receives to a Cloud Pub/Sub topic

- release-calendar/src/client/components/ChannelTable.tsx
- release-calendar/src/client/components/ReleaseCard.tsx
- release-calendar/src/client/stylesheets/_base.scss
- release-calendar/src/client/stylesheets/calendar.scss
- release-calendar/src/client/stylesheets/channelTable.scss
- release-calendar/src/server/app.ts
- release-calendar/src/server/repository-service.ts
- release-calendar/src/types.ts
- release-calendar/test/test-data.ts
Simplifies release calendar to only track % beta as "beta".
> [release-calendar] Remove opt-in beta as a channel

- owners/src/ownership/owners_check.js
- owners/test/index.test.js
- owners/test/ownership/owners_check.test.js
It's hard to notice in this screenshot, but the filename includes `__`, which makes a certain section render as bold.
The actual path is:
`.../extensions/__amp-component_name_hyphenated__/__component_version__/storybook/...`
but it looks like:
.../extensions/__amp-component_name_hyphenated__/__component_version__/storybook/...,
> Wrap filename in backticks to prevent accidental formatting

- pr-deploy/package-lock.json
- pr-deploy/package.json
v3 now only supports being imported as an [ECMAScript module](https://www.npmjs.com/package/node-fetch#loading-and-configuring-the-module), and our TS config is set to output CommonJS code - this PR reverts that change until we decide to migrate to ESM output
Tag-along: remove flags from `tsc` call, they're already included in the tsconfig.json file
> [pr-deploy] Revert node-fetch from v3.0.0 to v2.6.2

- project-metrics/metrics_service/apis/circleci.py
- project-metrics/metrics_service/apis/circleci_test.py
- project-metrics/metrics_service/database/models.py
- project-metrics/metrics_service/metrics/base.py
- project-metrics/metrics_service/metrics/cherrypick_issue_count_test.py
- project-metrics/metrics_service/metrics/circleci_flakiness.py
- project-metrics/metrics_service/metrics/circleci_flakiness_test.py
- project-metrics/metrics_service/metrics/circleci_greenness.py
- project-metrics/metrics_service/metrics/circleci_greenness_test.py
- project-metrics/metrics_service/metrics/circleci_presubmit_latency.py
- project-metrics/metrics_service/metrics/circleci_presubmit_latency_test.py
- project-metrics/metrics_service/server.py
The first step to updating the project metrics dashboard to show data from CircleCI rather than Travis is to create the apis and metrics objects to obtain and display data from CircleCI
> Add circleci api and metrics to project-metrics

- renovate.json
v3 now only supports being imported as an ECMAScript module, and our TS config is set to output CommonJS code - this PR reverts that change until we decide to migrate to ESM output
> [meta] Lock `node-fetch` to SemVer 2.x

- bundle-size-chart/static/index.html
- bundle-size-chart/static/index.js
- Dark mode.
- Expands chart to fill viewport. 
- Allows zooming in on a time range by clicking and dragging (!)
- Hover indicator dots are clickable. Labels are now nudged when reaching the edge, so they never truncate.
- Sets a hash so that query and time range filters are shareable by URL.
Demo on [canyon-subsequent-sea.glitch.me](https://canyon-subsequent-sea.glitch.me) (data may be stale).
> Improve usability of `bundle-size-chart`

- percy-mirror-verifier/test/server.test.ts
One test currently fails for a super weird reason: the merge commit https://github.com/ampproject/amp-github-apps/commit/9bb19928290191c09246a5f7c4f6f77ac6ed9390 does not match the single commit https://github.com/ampproject/amp-github-apps/pull/1566/commits/93a16816dc8c307babde226d3e131e07b42d697b of this PR https://github.com/ampproject/amp-github-apps/pull/1566
This line is missing from the merge commit, which then breaks main:
https://github.com/danielrozenberg/amp-github-apps/blob/93a16816dc8c307babde226d3e131e07b42d697b/percy-mirror-verifier/test/server.test.ts#L203
> Fix `percy-mirror-verifier` test

- bundle-size-chart/app.yaml
- bundle-size/app.yaml
- error-monitoring/app.yaml
- owners/app.yaml
- percy-mirror-verifier/app.yaml
- release-calendar/app.yaml
- webhook-pubsub-publisher/app.yaml
Cloud builds are [failing](https://pantheon.corp.google.com/cloud-build/builds/c9201ea3-4ddc-40da-8953-8318c463f515;step=3?project=ampproject-owners-bot) because deps now require higher Node versions, but for some reason GCP defaults us to Node v12
This PR pins to v18 as detailed in https://cloud.google.com/appengine/docs/flexible/nodejs/runtime#newversions
> Pin Node to v18 in all app.yaml files

- invite/cloud_build.yaml
- onduty/cloud_build.yaml
https://cloud.google.com/functions/docs/migrating/nodejs-runtimes
> Pin Node to v18 for Cloud Functions

- invite/package.json
- onduty/package.json
Since April this year, Cloud Functions attempt to run the build step for the deployed code - we already pre-compile the deployed code during the Cloud Build step, and we don't upload the TS sources, so deployments fail unless we skip the build as recommended [here](https://cloud.google.com/functions/docs/release-notes#April_11_2023)
> Skip GCP build step for Cloud Functions

- bundle-size-chart/package-lock.json
- bundle-size-chart/package.json
- bundle-size-chart/src/app.ts
This is apparently the new recommended way of creating Octokit instances. Also, older fixed deep-dependency versions in package-lock.json were causing type errors, so I had to delete and regenerate that file
> Fix `bundle-size-chart` octokit dependencies

- bundle-size-chart/.gcloudignore
- bundle-size-chart/app.yaml
I'm not sure why, but the flexible environment is failing to deploy. I tested the standard environment and it seems to work well, and it sort of [makes sense for this low-traffic project](https://cloud.google.com/appengine/docs/the-appengine-environments) anyways - so let's just switch it and not thing about it anymore :)
> Switch `bundle-size-chart` to GAE standard environment

- error-monitoring/src/app.ts
Encountering this error after #2222. This PR seems to fix it (tested locally and on a dev gcloud instance)
```
SyntaxError: The requested module 'body-parser' does not provide an export named 'json'
```
> [error-reporting] Typing fix
